#!/usr/bin/env python3
"""
Replace duplicated generic 10-section tails in level3.ts (100 occurrences).

BLOCK_END is the Level 3 Notes line (PEP 8), not Level 2 PEMDAS or Level 1 isinstance.
Avoid backticks inside strings (TS template literal / esbuild safety).
"""
from __future__ import annotations

from pathlib import Path

BLOCK_START = (
    "Key Concepts:\n"
    "• See the key concepts and explanation above for the main ideas and bullet points.\n\n"
    "Key Distinctions:"
)

BLOCK_END = (
    "Notes:\n"
    "• Follow PEP 8 and best practices; refer to the official docs for full details."
)

QUESTIONS: list[str] = [
    "Result of True and False?",
    "Result of True or False?",
    "Result of False and False?",
    "Result of False or False?",
    "Result of True and True?",
    "Result of True or True?",
    "Result of not True?",
    "Result of not False?",
    "Result of not (True and False)?",
    "Result of not True or False?",
    "Result of 10 > 5?",
    "Result of 5 < 10?",
    "Result of 10 >= 10?",
    "Result of 5 <= 10?",
    "Result of 10 == 10?",
    "Result of 10 != 5?",
    "Result of 5 > 10?",
    "Result of 10 < 5?",
    "Result of 10 == 5?",
    "Result of 5 >= 10?",
    "Result of 5 == 5?",
    "Result of 5 is 5?",
    "Result of [1, 2] == [1, 2]?",
    "Result of [1, 2] is [1, 2]?",
    'Result of "hello" == "hello"?',
    'Result of "hello" is "hello"?',
    "Result of None == None?",
    "Result of None is None?",
    "Result of 5 is not 10?",
    "What is the difference between == and is?",
    "Result of 5 < 10 < 15?",
    "Result of 15 > 10 > 5?",
    "Result of 5 <= 10 <= 15?",
    "Result of 15 >= 10 >= 5?",
    "Result of 5 == 5 == 5?",
    "Result of 5 != 10 != 15?",
    "Result of 5 < 10 < 5?",
    "Result of 10 < 5 < 15?",
    "Result of 5 < 15 < 10?",
    "Result of 5 == 5 == 10?",
    "Result of 5 in [1, 2, 3, 4, 5]?",
    "Result of 10 in [1, 2, 3, 4, 5]?",
    "Result of 5 not in [1, 2, 3]?",
    "Result of 1 not in [1, 2, 3]?",
    "Result of 'a' in 'abc'?",
    "Result of 'x' in 'abc'?",
    "Result of 'ab' in 'abc'?",
    "Result of 'ac' in 'abc'?",
    "Result of '' in 'abc'?",
    "Result of 'x' not in 'abc'?",
    "If x = 0, is x Truthy?",
    "If x = 1, is x Truthy?",
    "If x = [], is bool(x) True?",
    "If x = [1, 2], is x Truthy?",
    'If x = "", is x Truthy?',
    'If x = "hello", is x Truthy?',
    "If x = None, is x Truthy?",
    "If x = {}, is x Truthy?",
    "If x = {1: 2}, is x Truthy?",
    "If x = (), is x Truthy?",
    "Which keyword links if and else?",
    "Can you have an 'if' without an 'else'?",
    "Can you have multiple 'elif' statements?",
    "What happens if all conditions in if/elif are False?",
    "What happens if no 'else' and all conditions are False?",
    "Which operator checks inequality?",
    "Which operator checks identity?",
    "What is the syntax for if statement?",
    "What is the syntax for else statement?",
    "What is the syntax for elif statement?",
    "What is 5 if 5 > 3 else 3?",
    "What is 3 if 3 > 5 else 5?",
    "What is 'yes' if True else 'no'?",
    "What is 'yes' if False else 'no'?",
    "What is max(5, 3) if 5 > 3 else min(5, 3)?",
    "What is 'even' if 4 % 2 == 0 else 'odd'?",
    "What is 'even' if 5 % 2 == 0 else 'odd'?",
    "What is 'positive' if 5 > 0 else 'non-positive'?",
    "What is 'positive' if -5 > 0 else 'non-positive'?",
    "What is 'empty' if len([]) == 0 else 'not empty'?",
    "What is True and 5?",
    "What is False and 5?",
    "What is True or 5?",
    "What is False or 5?",
    "What is 0 and 5?",
    "What is 1 and 5?",
    "What is 0 or 5?",
    "What is 1 or 5?",
    "What is '' and 'hello'?",
    "What is 'hello' and 'world'?",
    "Result of 5 > 3 and 10 > 5?",
    "Result of 5 > 10 and 10 > 5?",
    "Result of 5 > 3 or 10 < 5?",
    "Result of 5 > 10 or 10 < 5?",
    "Result of not (5 > 10)?",
    "Result of not (5 > 3)?",
    "Result of 5 > 3 and not (10 < 5)?",
    "Result of 5 in [1, 2, 3] or 10 > 5?",
    "Result of 5 in [1, 2, 3] and 10 > 5?",
    "Result of (5 > 3) == (10 > 5)?",
]


def _sec(title: str, *bullets: str) -> str:
    body = "\n".join("• " + b for b in bullets)
    return f"{title}\n{body}"


def _tail(
    kd1: str,
    kd2: str,
    how: str,
    step: str,
    order: str,
    common: str,
    edge: str,
    perf: str,
    ex: str,
    notes: str,
) -> str:
    return "\n\n".join(
        [
            _sec("Key Distinctions:", kd1, kd2),
            _sec("How It Works:", how),
            _sec("Step-by-Step Execution:", step),
            _sec("Order of Operations:", order),
            _sec("Common Use Cases:", common),
            _sec("Edge Cases:", edge),
            _sec("Performance Considerations:", perf),
            _sec("Examples:", ex),
            _sec("Notes:", notes),
        ]
    )


TAIL_ROWS: list[tuple[str, str, str, str, str, str, str, str, str, str]] = [
    (
        "and is logical conjunction: both operands must be truthy for the result to be True.",
        "or with the same pair would be True because the left operand True is enough.",
        "Python evaluates both literal booleans; the right side is falsy, so and yields False.",
        "1. Evaluate True. 2. Evaluate False. 3. Apply and -> False.",
        "and has lower precedence than not; no not in this expression.",
        "Requiring every flag in a compound permission check.",
        "With objects, and returns the first falsy value or the last truthy one.",
        "Constant-time on bools.",
        "True and True -> True; True and 0 -> 0 (short-circuit on falsy).",
        "Prefer explicit if x is not None over truth tests when None is special.",
    ),
    (
        "or returns True when at least one operand is True; True on the left is sufficient.",
        "and(True, False) would be False — stricter than this or expression.",
        "The first operand True makes or True without needing the second for the boolean outcome.",
        "1. Left operand True. 2. or short-circuits to True for this bool case.",
        "or binds less tightly than conditional if-else; not used here.",
        "Default parameters, feature toggles, validation with multiple allowed passes.",
        "or among objects returns the first truthy object, not necessarily True.",
        "Trivial cost.",
        "False or True -> True; [] or 'default' -> 'default'.",
        "Chain: label or 'unknown' for optional strings.",
    ),
    (
        "and needs both sides truthy; two False operands cannot yield True.",
        "or(False, False) is also False, but only one operand needs to be True for or to succeed.",
        "Both operands are False, so conjunction is False.",
        "1. Left False. 2. Right False. 3. and -> False.",
        "Plain boolean and without not or comparisons.",
        "Showing that two guards both failed.",
        "Short-circuit: second operand still evaluated for literal False and False.",
        "Negligible.",
        "False and True -> False.",
        "Combine with not for De Morgan rewrites in larger predicates.",
    ),
    (
        "or is False only when no operand is truthy; both operands are False here.",
        "and(False, False) is False for a different logical reason (conjunction).",
        "Neither side is True, so or produces False.",
        "1. First False. 2. Second False. 3. or -> False.",
        "Single or of two booleans.",
        "Reporting that every branch in an or-chain failed.",
        "or among many literals: any True would flip the result.",
        "Trivial.",
        "False or False -> False; True or False -> True.",
        "any([a, b, c]) mirrors repeated or for iterables.",
    ),
    (
        "Both conjuncts are True, so the compound boolean is True.",
        "or(True, True) is True but does not model mutual requirement like and does.",
        "and is True only when every operand is truthy — satisfied here.",
        "1. Left True. 2. Right True. 3. and -> True.",
        "Boolean and of two constants.",
        "All preconditions met before a critical action.",
        "Mixing ints: 3 and 5 returns 5, not True — watch types.",
        "Instant.",
        "True and True -> True.",
        "Use all(iterable) for many conjuncts instead of long and chains.",
    ),
    (
        "or is True if any operand is True; two Trues still yield True.",
        "and(True, True) also yields True but with different meaning (all must hold).",
        "Either True makes or succeed; both are True here.",
        "1. Left True. 2. or is already satisfied — result True.",
        "or of two boolean literals.",
        "Redundant OR in generated or hand-written quizzes — simplify when reviewing.",
        "First truthy wins for object operands.",
        "Trivial.",
        "True or False -> True.",
        "Avoid or True at end of expression unless documenting intent.",
    ),
    (
        "not inverts truth: True becomes False.",
        "Bitwise ~ is different — it operates on integer bits, not logical not.",
        "Unary not applies directly to True.",
        "1. Operand True. 2. not yields False.",
        "not has high precedence; applies to True only.",
        "Negating a single boolean flag.",
        "not not x is x for proper booleans.",
        "Trivial.",
        "not False -> True.",
        "Use if not items: for empty containers — truthiness, not explicit not on list.",
    ),
    (
        "not False is True — double negation of False returns to truth.",
        "Comparing with == False is not the same as not, though results can match for bools.",
        "Unary not on False yields True.",
        "1. Operand False. 2. not -> True.",
        "Single not on a bool.",
        "Flipping a guard to allow the happy path.",
        "not 0 is True because 0 is falsy — different mechanism, same keyword.",
        "Trivial.",
        "not True -> False.",
        "Prefer explicit is False for sentinel checks when None and False differ.",
    ),
    (
        "Parentheses force (True and False) to False first; not then yields True.",
        "Without parens, not True and False parses as (not True) and False — a classic trap.",
        "Inner and is False; not negates it to True.",
        "1. True and False -> False. 2. not False -> True.",
        "not applies to the parenthesized subexpression, not to True alone.",
        "Negating a compound business rule for alternative logic.",
        "Always parenthesize when mixing not with and/or for readers and parsers.",
        "Trivial.",
        "not (A and B) differs from (not A) and B.",
        "Document operator precedence in team style guides.",
    ),
    (
        "not binds tighter than or: this parses as (not True) or False, not not(True or False).",
        "(not True) is False; False or False is False — different from not(True or False) which is False too here.",
        "Left subexpression not True; then or with False.",
        "1. not True -> False. 2. False or False -> False.",
        "not before or at this precedence level.",
        "Illustrates why explicit parentheses beat memorizing tables alone.",
        "not (True or False) would be False — compare grouping on paper.",
        "Trivial.",
        "Add parentheses whenever reviewers misread precedence.",
        "PEP 8 encourages spacing that clarifies boolean expressions.",
    ),
    (
        "> compares numbers; 10 is greater than 5, so the comparison is True.",
        ">= would also be True here; < would be False with operands swapped.",
        "Rich comparison calls PyObject_RichCompare for ints; result is bool.",
        "1. Load 10 and 5. 2. Greater-than test. 3. True.",
        "Chained comparisons are separate; here one binary > only.",
        "Sorting decisions, thresholds, game scores.",
        "NaN comparisons are special with floats — not involved for small ints.",
        "O(1) integer compare.",
        "10 > 10 -> False; 5 > 5 -> False.",
        "Use key= when sorting objects instead of manual > chains.",
    ),
    (
        "< checks whether the left is strictly below the right; 5 < 10 is True.",
        "5 > 10 would be False — direction of inequality matters.",
        "Integer comparison without crossing zero issues for these magnitudes.",
        "1. Compare 5 and 10. 2. True because 5 is less.",
        "Single comparison operator.",
        "Range checks before indexing or clamping.",
        "Comparing mixed int and float promotes to float — still fine here.",
        "Constant time.",
        "5 < 5 -> False; 10 < 5 -> False.",
        "Pair with <= for inclusive bounds: a <= x <= b.",
    ),
    (
        ">= means greater or equal; 10 >= 10 tests boundary equality.",
        "Pure > would be False at 10 == 10; >= includes the tie.",
        "Comparison succeeds when left equals right for >=.",
        "1. Compare 10 and 10. 2. True because equality satisfies >=.",
        "One rich comparison.",
        "Loop bounds, inclusive maximums, score at least thresholds.",
        "Floating point equality at boundaries can surprise — use tolerances for floats.",
        "O(1).",
        "9 >= 10 -> False; 11 >= 10 -> True.",
        "math.isclose for float equality, not >= alone.",
    ),
    (
        "<= checks left at or below right; 5 <= 10 is True.",
        "5 >= 10 would be False — do not flip operands blindly.",
        "Inequality including equality differs from strict <.",
        "1. Take 5 and 10. 2. <= succeeds.",
        "Single <= operation.",
        "Inclusive upper limits, validating user age caps.",
        "Chained 5 <= x <= 10 reads like math; single <= is a building block.",
        "Trivial for small ints.",
        "5 <= 5 -> True.",
        "Combine with >= for rectangle membership tests.",
    ),
    (
        "== tests value equality; two ints with the same value compare True.",
        "is would be True for small int caching but is a different notion — see other questions.",
        "Equality comparison for 10 and 10 yields True.",
        "1. Load both 10. 2. Value equality -> True.",
        "No chaining; one ==.",
        "Asserting computed results match expected constants.",
        "Large ints and floats near equality need care — not this exact int case.",
        "O(1) for small ints.",
        "10 == 11 -> False.",
        "Use == for content; is for identity.",
    ),
    (
        "!= tests inequality; 10 differs from 5, so the result is True.",
        "10 == 5 would be False — opposite operator.",
        "Not-equal returns True when values differ.",
        "1. Compare 10 and 5. 2. Not equal -> True.",
        "Single !=.",
        "Rejecting duplicates, validating inputs differ.",
        "nan != nan is True in IEEE floats — reflexivity breaks.",
        "Constant time.",
        "5 != 5 -> False.",
        "Pair != with in for membership negation patterns.",
    ),
    (
        "> with left smaller than right yields False; 5 is not greater than 10.",
        "5 < 10 is the True version with operands in natural ascending order.",
        "Comparison fails because the ordering is wrong for >.",
        "1. Evaluate 5 > 10. 2. False.",
        "One > without chaining.",
        "Detecting failed threshold checks.",
        "Mixed types follow comparison rules; both ints here.",
        "Trivial.",
        "5 > 4 -> True.",
        "Sort key errors often show up as unexpected > results.",
    ),
    (
        "10 < 5 is False because ten is not less than five.",
        "5 > 10 is the same ordering fact stated differently — also False for the analogous question.",
        "Left operand is not strictly below the right.",
        "1. Compare 10 and 5. 2. False.",
        "Single <.",
        "Catching invalid ordering in data pipelines.",
        "Lexicographic tuple comparison differs — not two plain ints.",
        "O(1).",
        "3 < 10 -> True.",
        "Use chained comparisons for readable between checks.",
    ),
    (
        "== requires identical values; 10 and 5 differ, so result is False.",
        "10 != 5 would be True — opposite polarity.",
        "Equality fails for distinct integers.",
        "1. Compare 10 and 5. 2. False.",
        "One == comparison.",
        "Guarding that two computed paths matched before merging.",
        "Same value different types: 1 == True is True — watch bool/int quirks.",
        "Trivial.",
        "10 == 10 -> True.",
        "Use Decimal for money, not raw == on floats.",
    ),
    (
        ">= fails when the left is strictly below the right; 5 is not >= 10.",
        "5 <= 10 would be True — flip operator and operands carefully.",
        "Boundary: 5 >= 5 would be True — here 10 is larger.",
        "1. Test 5 >= 10. 2. False.",
        "Single >=.",
        "Minimum score not met scenarios.",
        "Floating rounding could nudge values across boundaries.",
        "Trivial.",
        "10 >= 5 -> True.",
        "Inclusive vs exclusive bounds in APIs.",
    ),
    (
        "== with the same literal on both sides is True for integers.",
        "is may also be True for small ints due to caching — a separate question.",
        "Value equality holds for 5 and 5.",
        "1. Compare 5 and 5. 2. True.",
        "One equality check.",
        "Verifying symmetric calculations.",
        "Different objects with same value: lists need ==, not identity.",
        "O(1).",
        "5 == 6 -> False.",
        "defaultdict behavior vs explicit key checks — different patterns.",
    ),
    (
        "is tests object identity; small integers may share one cached int object in CPython.",
        "== would still be True for value equality even if identities differ.",
        "5 is 5 is typically True because both refer to the same small-int singleton.",
        "1. Compare identities of two int 5. 2. True in common builds.",
        "is is not overloaded like == for custom classes by default.",
        "Fast path for None checks: x is None.",
        "Do not rely on int caching for is across computations — use == for value.",
        "Identity compare is pointer equality in CPython.",
        "a is b for large computed ints may be False even if a == b.",
        "PEP 8: always is None, never == None.",
    ),
    (
        "== compares element-wise list contents; matching sequences compare equal.",
        "is would be False for two distinct list objects with same items — different question.",
        "List equality uses recursive element comparison for contents.",
        "1. Build or reference two lists. 2. Compare elements. 3. True.",
        "== can invoke __eq__ on elements; nested structures recurse.",
        "Testing expected output lists in unit tests.",
        "Subclasses may override list equality — edge for advanced code.",
        "O(n) in list length.",
        "[1] == [2] -> False.",
        "Use == for value; is only if same object is intended.",
    ),
    (
        "is checks whether two names refer to the same object; two list literals are distinct objects.",
        "== can still be True for same contents — identity is stricter.",
        "Each [1, 2] literal constructs a new list in CPython.",
        "1. Create first list. 2. Create second list. 3. is -> False.",
        "Two separate allocations mean different ids.",
        "Avoid using is for list content comparison.",
        "Singleton empty tuple () is shared — lists are never shared like that.",
        "Two allocations cost more than one, but quiz focuses on identity.",
        "id(a) == id(b) matches is for objects.",
        "Copy lists with list(x) or x[:] when you need a duplicate.",
    ),
    (
        "str == compares character content; identical strings compare True.",
        "is may be True for interned identical string literals in one expression — implementation detail.",
        "Unicode code points match for both hello literals.",
        "1. Load two str objects. 2. Value equality -> True.",
        "Case sensitivity matters: Hello != hello.",
        "Comparing user input after normalization.",
        "Very long strings: equality still compares content — can be costly.",
        "O(n) in string length worst case.",
        "hello == Hello -> False.",
        "Normalize with casefold() for case-insensitive logic.",
    ),
    (
        "String literals with same text may be interned; is can be True for shared literals.",
        "== is the portable way to compare string value; is is identity.",
        "Implementation may intern identical literals in the same statement context.",
        "1. Create or intern strings. 2. is compares identity.",
        "Do not depend on str interning for program logic.",
        "Always use == for string value in portable code.",
        "Computed strings: hello = 'he'+'llo'; another 'hello' may not share id.",
        "Identity check is O(1) pointer compare.",
        "Use is for singletons like None only in typical style.",
        "str.intern exists for explicit interning — rare.",
    ),
    (
        "None == None compares values; None is a singleton so equality holds.",
        "is None is the idiomatic check — still, == works between two None values.",
        "There is only one None object in Python.",
        "1. Compare None to None. 2. True.",
        "== for None is acceptable but is None is preferred for clarity.",
        "Optional values defaulting to sentinel None.",
        "np.nan == np.nan is False — None is not like float nan.",
        "Trivial.",
        "x == None works but style guides forbid it.",
        "Always write is None and is not None.",
    ),
    (
        "is None checks identity with the sole None singleton — the idiomatic None test.",
        "== None compares by value and is discouraged by PEP 8 even though it often works.",
        "None is None is True because both sides name the same object.",
        "1. Load None twice. 2. Identity succeeds.",
        "is compares object id, not user-defined __eq__ for this built-in case.",
        "Guarding optional parameters and search misses.",
        "numpy array equality overloads — not relevant to None itself.",
        "Pointer compare.",
        "type(None)() is invalid — None is not callable.",
        "Never chain: if x is None or y is None reads clearly.",
    ),
    (
        "is not checks that two objects are not the same; 5 and 10 are different ints.",
        "!= compares values; 5 != 10 is also True but does not speak about object identity.",
        "Small ints may be cached, but 5 and 10 are different identities.",
        "1. Left int 5. 2. Right int 10. 3. is not -> True.",
        "is not is the negation of is.",
        "Rejecting mistaken object reuse when ids must differ.",
        "After large arithmetic, int identity may differ from literals — use == for value.",
        "Identity compare is O(1).",
        "5 is not 5 is False.",
        "Use is not None for explicit optional handling.",
    ),
    (
        "== tests value equality via __eq__; is tests object identity (same id).",
        "For lists and dicts, == compares contents; is is often False for separate literals.",
        "None and small ints are special cases where is sometimes matches user intuition.",
        "1. Decide whether you care about value or identity. 2. Pick == or is.",
        "Different contexts: dedup caches vs business equality.",
        "Data modeling: when two records represent the same entity.",
        "NaN breaks == reflexivity; None is a singleton.",
        "== may call expensive __eq__ on large objects.",
        "a == b does not imply a is b.",
        "Document which semantics your API expects in docstrings.",
    ),
    (
        "Chained comparisons expand to a and b and c: 5 < 10 and 10 < 15.",
        "Writing 5 < 10 and 10 < 15 manually duplicates the middle value — chaining avoids that.",
        "Each segment must hold for the whole chain to be True.",
        "1. Test 5 < 10. 2. Test 10 < 15. 3. Both True -> True.",
        "Chained ops use same middle operand only once — fewer typo risks.",
        "Validating a value sits inside an interval.",
        "NaN in any segment makes the chain False.",
        "Each comparison is O(1) for small numbers.",
        "5 < 10 < 5 is False because the second segment fails.",
        "Do not assume (a < b < c) == (a < b) and (b < c) with different b unless written.",
    ),
    (
        "Descending chain 15 > 10 > 5 means 15 > 10 and 10 > 5 — both true.",
        "Mixing directions in one chain without thought can confuse readers — here it is consistent.",
        "Each pairwise comparison must succeed.",
        "1. 15 > 10 True. 2. 10 > 5 True. 3. Chain True.",
        "Chained comparisons are pairwise, not transitive inference in one step.",
        "Monotonic sequences in dashboards or ranking checks.",
        "Floating point equality at boundaries can break strict chains.",
        "O(1) for literals.",
        "15 > 10 > 15 is False.",
        "Use math.isclose when comparing computed floats in chains.",
    ),
    (
        "Inclusive chain 5 <= 10 <= 15 allows endpoints; 10 equals 10 and 10 <= 15.",
        "Strict < on both ends would be a narrower band.",
        "Both bounds must be satisfied simultaneously.",
        "1. 5 <= 10 True. 2. 10 <= 15 True. 3. True.",
        "Chained <= mixes well with date ranges.",
        "API rate limits often use inclusive minutes.",
        "Timezone-aware datetimes: compare like types only.",
        "Constant-time on simple scalars.",
        "5 <= 10 <= 9 is False.",
        "For half-open intervals prefer explicit variables for bounds.",
    ),
    (
        "Non-increasing chain 15 >= 10 >= 5 mirrors descending comparisons with inclusive ties.",
        "Each adjacent pair must hold; 10 is both upper and middle pivot.",
        "Both >= segments must be True.",
        "1. 15 >= 10 True. 2. 10 >= 5 True. 3. Chain True.",
        "Same mechanics as ascending chains, only operators flipped.",
        "Score must stay within a corridor as it drops.",
        "Off-by-one at boundaries: draw a number line.",
        "O(1).",
        "15 >= 10 >= 11 is False.",
        "Prefer named variables for thresholds when teaching.",
    ),
    (
        "Repeated == chains: 5 == 5 == 5 expands to (5 == 5) and (5 == 5) with shared middle.",
        "Unlike math, Python evaluates each relation; all must hold.",
        "All three literals are 5, so equality holds every time.",
        "1. First pair True. 2. Second pair True. 3. True.",
        "Chained == is still pairwise comparisons.",
        "Asserting three values match in logging or tests.",
        "Float noise: 0.1+0.2 may break naive triple equality.",
        "Three comparisons.",
        "a == b == c is not the same as (a,b,c) == (x,y,z) in one shot.",
        "Use collections.Counter for multiset equality.",
    ),
    (
        "Chained != compares pairwise: 5 != 10 and 10 != 15 — both must be True.",
        "This is not the same as (5 != 10 != 15) with a different middle — watch the middle.",
        "Each adjacent inequality must hold.",
        "1. 5 != 10 True. 2. 10 != 15 True. 3. True.",
        "Chained != useful for strictly increasing distinct samples.",
        "Ensuring three samples are pairwise distinct.",
        "If middle equals an endpoint, chain fails.",
        "O(1) for small ints.",
        "5 != 5 != 5 is False at the first pair.",
        "For many values, use len(set(values)) == len(values).",
    ),
    (
        "Chain 5 < 10 < 5 fails because 10 < 5 is False even though 5 < 10 is True.",
        "Transitivity of numbers does not mean any chained write is valid — each segment is checked.",
        "The middle value cannot be both above 5 and below 5 in this pattern.",
        "1. 5 < 10 True. 2. 10 < 5 False. 3. Short-circuit yields False.",
        "False at first failing segment stops the chain.",
        "Catching impossible range assumptions in validation.",
        "NaN comparisons always False — chain breaks.",
        "Constant-time.",
        "Draw intervals on a line to avoid impossible chains.",
        "Use separate named variables for clarity.",
    ),
    (
        "10 < 5 is False, so the chained comparison 10 < 5 < 15 fails at the first segment.",
        "The right segment is never evaluated if using short-circuit — actually Python evaluates all parts for chained comparisons.",
        "Actually Python evaluates each comparison; first False makes overall False.",
        "1. 10 < 5 False. 2. Entire chain False.",
        "Chained form still evaluates middle for the second segment in CPython — study docs for exact semantics.",
        "Rejecting bad sensor readings that fail the first threshold.",
        "Understanding CPython evaluation order for chained ops is worth reading once.",
        "Small ints.",
        "5 < 10 < 15 True.",
        "Prefer explicit variables for thresholds in production code.",
    ),
    (
        "5 < 15 < 10 fails because 15 < 10 is False — order is not sorted.",
        "Middle value must be both greater than left and less than right for ascending < chains.",
        "Second segment fails.",
        "1. 5 < 15 True. 2. 15 < 10 False. 3. False.",
        "Chained comparisons are local checks, not global sorting.",
        "Detecting that a reported triple is not monotonic.",
        "Dates: ensure ascending order before chaining.",
        "O(1).",
        "Sort three numbers then compare.",
        "Use sorted([a,b,c]) == [a,b,c] for order check.",
    ),
    (
        "5 == 5 == 10 fails because 5 == 10 is False.",
        "First pair True but second pair compares middle to the right literal.",
        "Chained equality requires every adjacent pair to match.",
        "1. 5 == 5 True. 2. 5 == 10 False. 3. False.",
        "Middle 5 must equal both neighbors — impossible with 10 on the right.",
        "Catching inconsistent triples in puzzles.",
        "Use all_equal helper for clarity.",
        "Two equality checks.",
        "a == b == c requires b equal to both a and c.",
        "For floats, use isclose.",
    ),
    (
        "Membership: 5 is in the list literal — containment test scans the list.",
        "== would compare value to the whole list — not what in does.",
        "in calls __contains__ on the container, list scans until match.",
        "1. Iterate conceptually. 2. Find 5. 3. True.",
        "in has lower precedence than comparisons; not used with other ops here.",
        "Checking allowlists and roles.",
        "Custom objects need __contains__ or iterable protocol.",
        "O(n) for list length.",
        "5 in [5,5,5] is True early.",
        "Use set for large membership tables.",
    ),
    (
        "10 is not in the list [1..5] — linear search finds no match.",
        "in would be False; not in is not needed here.",
        "Membership fails for 10.",
        "1. Scan elements. 2. No 10. 3. False.",
        "10 != 5 is unrelated — membership is different.",
        "Rejecting user IDs not in a small cohort.",
        "Nested lists: 10 in [[10]] is False.",
        "O(n) scan.",
        "10 in [10] is True.",
        "bisect for sorted lists when searching.",
    ),
    (
        "5 not in [1,2,3] succeeds because 5 is absent from the short list.",
        "5 in [1,2,3] would be False — not in negates membership.",
        "not in is the negation of in.",
        "1. Evaluate membership. 2. Apply not. 3. True.",
        "not in reads as a single operator spelling.",
        "Deny lists for access control.",
        "Default __contains__ for dict checks keys.",
        "O(n) for list.",
        "5 in [5] is True.",
        "Prefer set for O(1) average membership.",
    ),
    (
        "1 not in [1,2,3] is False because 1 is the first element.",
        "not in must be false when the item is present.",
        "Membership finds 1 immediately.",
        "1. Check first element. 2. Found. 3. not in -> False.",
        "Early exit on match for list.",
        "Validating a value is not in a deny list when it actually is.",
        "Empty list: no membership.",
        "Best case O(1) when first match.",
        "1 not in [] is True.",
        "Use sets for uniqueness checks.",
    ),
    (
        "Substring test: 'a' in 'abc' scans character sequence — True.",
        "in on str checks contiguous substrings, not arbitrary subsequences.",
        "Unicode-aware: code points match.",
        "1. Search 'a' in 'abc'. 2. Found at index 0.",
        "in on str uses efficient algorithms in CPython.",
        "Token scanning, simple validation.",
        "Empty needle in str: '' in any string is True.",
        "O(n*m) in naive worst case; CPython optimized.",
        "'ab' in 'acb' is False.",
        "Use regex for complex patterns.",
    ),
    (
        "'x' does not appear in 'abc' — membership fails.",
        "Finding vs indexing: find returns -1, in returns False.",
        "Linear scan finds no match.",
        "1. Compare substrings. 2. False.",
        "Case sensitivity: 'A' in 'abc' is False.",
        "Rejecting invalid characters.",
        "Very long strings: build automaton for many queries.",
        "O(n) in length.",
        "'x' not in 'abc' is True.",
        "Use casefold for case-insensitive membership.",
    ),
    (
        "Multi-character substring 'ab' is contiguous in 'abc' — True.",
        'Single characters "a","b","c" differ from two-char "ab".',
        "Starts at index 0.",
        "1. Try match at 0. 2. 'ab' matches.",
        "in for multi-char is still contiguous window.",
        "Prefix checks before parsing.",
        "'ac' in 'abc' is False — not contiguous.",
        "O(n) in string length.",
        "'abc' in 'abc' is True.",
        "startswith is clearer for prefix-only checks.",
    ),
    (
        "Letters 'a' and 'c' are not adjacent in 'abc' — 'ac' is not a contiguous substring.",
        "in does not skip characters for substring search.",
        "No window matches 'ac'.",
        "1. Scan windows. 2. No match.",
        "Contrast with substring in bioinformatics.",
        "Typo detection: missing letter breaks contiguous match.",
        "O(n) scan.",
        "Use in for simple; use difflib for fuzzy similarity.",
        "Regular sets of characters are different from substring.",
        "KMP or Boyer-Moore appear in advanced search — not needed for quiz trivia.",
    ),
    (
        "Empty string is a substring of every string — vacuously at every position.",
        "Edge case: '' in 'abc' is True.",
        "CPython treats empty needle as always found.",
        "1. Evaluate ''. 2. Trivially contained.",
        "Useful for base cases in recursive string algorithms.",
        "Splitting on '' is different — not recommended.",
        "O(1) special case.",
        "'' in '' is True.",
        "Guard against empty delimiter bugs in split.",
        "str.count('') used to raise; behavior can differ by version — avoid relying on it.",
    ),
    (
        "not in negates membership; 'x' absent from 'abc' gives True.",
        "'x' in 'abc' is False.",
        "Boolean negation of in.",
        "1. in -> False. 2. not in -> True.",
        "not in reads as one operator family.",
        "Allowlist characters not in forbidden set.",
        "Same complexity as in.",
        "Prefer if c not in s: for readability.",
        "Use sets for large alphabets.",
        "operator.contains(container, item) mirrors the in protocol for generic code.",
    ),
    (
        "Numeric zero is falsy; bool(0) is False — the question asks if x is truthy.",
        "Non-zero ints are truthy; zero is the classic falsy counterexample.",
        "Truthiness uses __bool__ for int, zero is False.",
        "1. Take 0. 2. Convert to bool. 3. False.",
        "if x: branches on truthiness, not explicit == True.",
        "Guarding divisions and defaulting empty counts.",
        "False is subclass of int in a sense — avoid mixing in arithmetic.",
        "Trivial.",
        "bool(0.0) is also False.",
        "Use is not None when 0 is a valid value.",
    ),
    (
        "Integer one is truthy; bool(1) is True.",
        "Only zero among ints is falsy in truthiness.",
        "Non-zero ints are True in boolean context.",
        "1. Take 1. 2. bool -> True.",
        "Truthiness before logical operators.",
        "Counters and flags represented as ints.",
        "Negative ints are truthy too.",
        "Trivial.",
        "bool(-1) is True.",
        "Explicit comparisons for API clarity.",
    ),
    (
        "Empty list is falsy; bool([]) is False — the question asks if bool is True.",
        "Non-empty list is truthy; empty container is empty.",
        "len([]) == 0 correlates with falsy.",
        "1. Evaluate []. 2. __bool__ uses len; 0 -> False.",
        "Containers implement __bool__ via length.",
        "Checking for work before processing.",
        "Empty vs None: [] is falsy but is not None.",
        "O(1) for list length.",
        "bool([False]) is True because list is non-empty.",
        "Use if not items: for empty sequences.",
    ),
    (
        "Non-empty list [1,2] is truthy — len > 0.",
        "[] is falsy; this list has elements.",
        "Elements need not be truthy themselves; container length matters.",
        "1. List has items. 2. bool True.",
        "Nested lists: outer truthiness from length.",
        "Processing queues with pending jobs.",
        "List of all falsy elements is still truthy if non-empty.",
        "O(1) length check.",
        "if lst: is idiomatic.",
        "Beware of huge lists — truthiness only checks emptiness.",
    ),
    (
        "Empty string is falsy; useful for optional input checks.",
        "Non-empty string is truthy even if only whitespace — strip first if needed.",
        "len('') == 0.",
        "1. ''. 2. bool False.",
        "Strings use length for truthiness.",
        "Form validation before database write.",
        "Whitespace-only ' ' is truthy.",
        "O(1).",
        "bool('0') is True.",
        "Use .strip() or explicit checks for UI fields.",
    ),
    (
        "Non-empty string 'hello' is truthy.",
        "Even a single character string is truthy.",
        "Content does not need to be 'truthy' in English sense — only non-empty.",
        "1. String has length > 0. 2. True.",
        "Same rule for all non-empty str.",
        "Guarding message bodies.",
        "Unicode empty string is still falsy.",
        "O(1) length.",
        "bool('False') is True — non-empty string.",
        "Do not confuse string 'False' with bool False.",
    ),
    (
        "None is falsy; bool(None) is False.",
        "None is its own type; no value means no truth.",
        "Testing if x is None is clearer than bool(x) for None.",
        "1. None. 2. __bool__ raises? No — None is falsy via __bool__ not defined — uses NoneType rules.",
        "Actually None is falsy by language definition.",
        "Optional values defaulting to None.",
        "Distinguish None from 0 and [].",
        "Trivial.",
        "if x is None: is preferred over not x when 0 is valid.",
        "Sentinel objects other than None need explicit rules.",
    ),
    (
        "Empty dict {} is falsy — no keys.",
        "Non-empty dict is truthy even if values are falsy.",
        "len({}) == 0.",
        "1. Empty mapping. 2. bool False.",
        "dict truthiness uses size, not values.",
        "Checking for configuration before use.",
        "Default dict with keys still truthy.",
        "O(1) length.",
        "bool({0: False}) is True.",
        "Use .get for missing keys.",
    ),
    (
        "Dict with one entry {1:2} is truthy — has keys.",
        "Empty {} is falsy; any key makes it truthy.",
        "Values can be anything; presence of keys matters.",
        "1. Non-empty dict. 2. True.",
        "Key existence drives truthiness.",
        "Caches and counters as dicts.",
        "Very large dicts still truthy if non-empty.",
        "O(1) emptiness check.",
        "if d: before iterating.",
        "Compare to None for unset vs empty dict.",
    ),
    (
        "Empty tuple () is falsy — zero-length sequence.",
        "Non-empty tuple truthy even if items falsy.",
        "Tuple length zero is the empty tuple singleton.",
        "1. (). 2. False.",
        "Immutable empty sequence.",
        "Function return () as no result.",
        "Singleton empty tuple () is shared.",
        "O(1).",
        "bool((0,)) is True.",
        "Named tuples follow same truthiness.",
    ),
    (
        "else is the keyword that pairs with if to introduce the alternative branch.",
        "elif adds extra tests before else; it is not the direct if/else link.",
        "if suite runs when condition true; else suite when all preceding tests failed.",
        "1. if cond. 2. optional elif ladder. 3. else for final fallback.",
        "else attaches to the nearest if at the same indentation.",
        "Explaining two-way branching to beginners.",
        "else on for/while means something different — no break took place.",
        "Parsing is indentation-based.",
        "else: after for runs if the loop finished without break.",
        "Read the language reference for the full compound-statement grammar.",
    ),
    (
        "else is optional; if alone can run a branch without alternative.",
        "If condition is False and nothing else, nothing runs.",
        "Single-branch conditionals are common.",
        "1. Evaluate condition. 2. Execute suite or skip.",
        "No else required.",
        "Early validation and guards.",
        "pass can be used as placeholder suite.",
        "Trivial cost.",
        "Combine with return for early exit style.",
        "PEP 8 spacing around if.",
    ),
    (
        "Multiple elif clauses are allowed — they test in order after the if fails.",
        "Each elif is another condition; first True wins.",
        "Ladder is like switch-case without fall-through.",
        "1. Test if. 2. elif chain until match. 3. else optional.",
        "elif shares same block level as if.",
        "HTTP status mapping, menu choices.",
        "Too many elifs: consider dict dispatch.",
        "Linear scan of conditions.",
        "match/case in 3.10+ for structural patterns.",
        "Keep elif bodies small for readability.",
    ),
    (
        "If all if and elif conditions are False and an else exists, else runs.",
        "Without else, nothing runs from that ladder.",
        "First True branch wins; if none, else catches.",
        "1. All tests False. 2. Jump to else.",
        "else attaches to this if chain only.",
        "Default handling in parsers.",
        "Ensure exhaustive elif for enums when possible.",
        "Worst case evaluates all conditions.",
        "assert never in else for impossible states — use sparingly.",
        "Consider match/case for clarity.",
    ),
    (
        "Without else, if all conditions False, nothing executes — no branch runs.",
        "Contrast with if/else where default runs.",
        "Silent skip is valid.",
        "1. Evaluate ladder. 2. None true. 3. Fall through.",
        "Optional side effects only on success.",
        "Feature flags that do nothing when off.",
        "Logging missing else may hide bugs.",
        "No cost if nothing runs.",
        "Explicit else: pass documents intent.",
        "Use elif True else or assert for debugging.",
    ),
    (
        "Inequality uses != or optionally <> in older docs — Python uses !=.",
        "== tests equality; != is its negation.",
        "Rich comparison != calls __ne__.",
        "1. Compare values. 2. Return not equal.",
        "!= and == have same precedence.",
        "Filtering distinct items.",
        "nan != nan is True in IEEE floats.",
        "Same cost as ==.",
        "1 != True is False in Python 3.",
        "Use != for value inequality.",
    ),
    (
        "Identity uses is and is not — same object in memory.",
        "== can be True while is is False for different objects with same value.",
        "Identity compares ids.",
        "1. Compare id(a) and id(b).",
        "is is not overloadable like == for custom classes by default.",
        "Singletons: None, small ints sometimes, empty tuple.",
        "CPython caches small ints — do not rely on is for values.",
        "Pointer compare.",
        "type(obj) is Foo vs isinstance — related pattern.",
        "Never compare str with is for value.",
    ),
    (
        "if statement syntax: if condition: suite — colon required.",
        "condition can be any expression; truthiness decides.",
        "Indentation defines the suite body.",
        "1. Evaluate condition. 2. If truthy, run suite.",
        "if is a compound statement header.",
        "Every branching program.",
        "Multiline condition with parentheses.",
        "Condition evaluated once.",
        "if x := expr: walrus in 3.8+.",
        "PEP 8: space after if.",
    ),
    (
        "else clause: else: suite — pairs with nearest if.",
        "elif is not else; else is the fallback.",
        "Runs when no if or elif matched.",
        "1. All tests false. 2. else suite.",
        "else aligns with if at same indent.",
        "Default paths.",
        "else with try/except/for differs.",
        "No condition on else.",
        "else: after for runs if no break.",
        "Keep else bodies short.",
    ),
    (
        "elif is not a standalone statement — it continues an if chain.",
        "Syntax: elif condition: suite — arbitrary many.",
        "elif is equivalent to nested else: if.",
        "1. Previous conditions false. 2. Test elif.",
        "elif at same indentation as if.",
        "Replacing nested if trees.",
        "match/case alternative for enums.",
        "Sequential evaluation.",
        "Convert long elif to dict lookup when possible.",
        "Document ordering when conditions overlap.",
    ),
    (
        "Conditional expression: x if cond else y — evaluates condition first.",
        "5 > 3 is True, so pick 5 not 3.",
        "Only one branch expression is evaluated.",
        "1. Test 5 > 3 True. 2. Result 5.",
        "Ternary has lower precedence than most operators — parenthesize.",
        "Inline min/max style choices.",
        "Do not put complex expressions without parens in ternary.",
        "Evaluates condition then one branch.",
        "a if b else c if d else e chains — careful.",
        "PEP 8 line breaks for long ternaries.",
    ),
    (
        "Condition 3 > 5 is False — else branch 5 is chosen.",
        "If true branch would run — here it does not.",
        "3 is not greater than 5.",
        "1. False condition. 2. Pick else 5.",
        "Ternary is expression, not statement.",
        "Defaulting when check fails.",
        "Ensure both branches are same type when possible.",
        "One branch evaluated.",
        "Use full if when branches have statements.",
        "Readable names for condition and values.",
    ),
    (
        "String literals with ternary: condition True picks yes.",
        "True is truthy — left branch.",
        "Result is 'yes'.",
        "1. True. 2. 'yes'.",
        "Ternary with strings.",
        "UI labels toggling.",
        "Unicode strings same rules.",
        "Trivial.",
        "False picks 'no' in sibling question.",
        "Multi-line strings in ternary need parentheses.",
    ),
    (
        "Condition False selects else branch 'no'.",
        "True branch skipped.",
        "Result 'no'.",
        "1. False. 2. 'no'.",
        "Ternary short-circuits branch evaluation.",
        "Error messages vs success labels.",
        "Avoid side effects in conditions.",
        "One branch runs.",
        "Compare to and/or trick for defaults.",
        "Keep conditions simple.",
    ),
    (
        "Nested condition: outer ternary chooses max(5,3) because 5>3 True.",
        "Inner max(5,3) is evaluated as the true branch expression.",
        "5 > 3 True — pick max(5,3) which is 5.",
        "1. Compare 5>3. 2. Evaluate max(5,3) -> 5.",
        "Ternary has lower precedence than calls — subexpressions parenthesized implicitly by structure.",
        "Compact numeric clamping patterns.",
        "Readability suffers if nested too deep.",
        "max evaluated only on chosen branch.",
        "Split into if/else for clarity in production.",
        "Use min/max builtins directly when simpler.",
    ),
    (
        "Parity check: 4 % 2 == 0 True — pick 'even'.",
        "Modulo zero means divisible by 2.",
        "Ternary maps bool to labels.",
        "1. 4%2==0 True. 2. 'even'.",
        "Combine % with comparison in condition.",
        "Formatting numbers as even/odd.",
        "Negative even: -4 % 2 == 0 in Python.",
        "Constant-time.",
        "5 % 2 == 0 False for odd.",
        "Use n & 1 for int bit parity in hot paths.",
    ),
    (
        "5 % 2 == 0 is False — 5 is odd.",
        "Else branch 'odd'.",
        "Ternary selects odd label.",
        "1. False condition. 2. 'odd'.",
        "Same pattern as even question with different n.",
        "Ticket numbering.",
        "Big integers support %.",
        "Trivial.",
        "Even test: n % 2 == 0 preferred to n % 2 == 1 for odd.",
        "Use divmod for quotient and remainder together.",
    ),
    (
        "Sign check: 5 > 0 True — 'positive'.",
        "Zero is not positive in this label scheme.",
        "Ternary on inequality.",
        "1. 5>0 True. 2. 'positive'.",
        "Could extend with elif for zero.",
        "Classifying numeric user input.",
        "-0.0 > 0 is False.",
        "Trivial.",
        "math.copysign for sign handling.",
        "Use Decimal for financial signs.",
    ),
    (
        "-5 > 0 is False — non-positive branch.",
        "Negative numbers are not positive.",
        "Else branch taken.",
        "1. False. 2. 'non-positive'.",
        "Inclusive zero would need separate test.",
        "Reporting loss vs gain.",
        "NaN comparisons are False — not this question.",
        "Trivial.",
        "Compare to sign() in numpy.",
        "Explicit zero handling when needed.",
    ),
    (
        "len([]) == 0 True — empty list string label.",
        "Non-empty would pick other branch.",
        "Ternary on emptiness.",
        "1. len 0. 2. 'empty'.",
        "len() is O(1) for lists.",
        "UI badges for empty state.",
        "len(None) raises — not used here.",
        "Trivial.",
        "if not seq: often clearer than len.",
        "Use truthiness directly for containers.",
    ),
    (
        "and with mixed types: True and 5 returns 5, the last evaluated truthy operand.",
        "and returns first falsy or last truthy — not necessarily bool.",
        "True is truthy — evaluate and return right side 5.",
        "1. True truthy. 2. Return 5.",
        "and short-circuits on falsy left.",
        "Default dict with or: {} or {} patterns differ.",
        "0 and 5 returns 0.",
        "Short-circuit skips right if left falsy.",
        "True and [] returns [].",
        "Document that boolean ops return operands in Python.",
    ),
    (
        "False and 5 short-circuits: False is falsy, so 5 is not evaluated.",
        "Result is False, not 5.",
        "and returns first falsy operand.",
        "1. False. 2. Stop with False.",
        "Right side not evaluated.",
        "Guarding expensive calls on left.",
        "Side effects on right skipped if left falsy.",
        "Relies on short-circuit.",
        "False and print() does not print.",
        "Use if for statements, not and trick.",
    ),
    (
        "True or 5 short-circuits on True — returns True without evaluating 5.",
        "or returns first truthy operand.",
        "Left True is enough.",
        "1. True. 2. Short-circuit True.",
        "Right side skipped.",
        "Default values: x or default.",
        "0 or 5 returns 5 — different pattern.",
        "Short-circuit semantics.",
        "True or heavy() skips heavy.",
        "Prefer explicit if for readability.",
    ),
    (
        "False or 5 evaluates False then 5 — returns 5 as first truthy.",
        "or returns first truthy or last falsy.",
        "False is falsy — move to right.",
        "1. False. 2. 5 truthy. 3. 5.",
        "Both operands evaluated until truthy found.",
        "Fallback values for falsy sentinels.",
        "[] or [1] -> [1].",
        "Two evaluates.",
        "Beware of valid falsy 0 with or.",
        "Use None-coalescing patterns carefully.",
    ),
    (
        "0 and 5 returns 0 — first falsy wins.",
        "0 is falsy; and does not reach 5.",
        "No boolean conversion unless in boolean context.",
        "1. 0 falsy. 2. Result 0.",
        "Short-circuit on falsy.",
        "Chaining validation with and.",
        "0 and expensive() skips expensive.",
        "and returns operand, not False.",
        "1 and 5 returns 5.",
        "if a and b: for clarity over truthy tricks.",
    ),
    (
        "1 and 5 returns 5 — both truthy, last evaluated.",
        "and returns last truthy if all truthy.",
        "1 is truthy; then evaluate 5.",
        "1. 1 truthy. 2. 5 truthy. 3. Return 5.",
        "No short-circuit early exit.",
        "Chaining defaults in fluent APIs.",
        "Empty string and 5 returns ''.",
        "Both sides evaluated.",
        "Compare to min(1,5) for numeric caps.",
        "All() on iterable is related.",
    ),
    (
        "0 or 5 returns 5 — first truthy after falsy 0.",
        "0 is falsy; or continues.",
        "5 is truthy — return 5.",
        "1. 0 falsy. 2. 5 truthy. 3. 5.",
        "or scans for first truthy.",
        "Default 0 to 5 pattern.",
        "0 or 0 or 0 returns 0.",
        "Evaluates until truthy.",
        "[] or [1] -> [1].",
        "Beware valid 0 with or.",
    ),
    (
        "1 or 5 returns 1 — first truthy short-circuits.",
        "5 does not run.",
        "or stops at first truthy.",
        "1. 1 truthy. 2. Return 1.",
        "Right skipped.",
        "Pick first configured flag.",
        "Non-zero ints are truthy.",
        "Short-circuit.",
        "or chain for priority list.",
        "Explicit None checks safer than or for defaults.",
    ),
    (
        "'' and 'hello' returns '' — empty string is falsy.",
        "and stops at first falsy.",
        "Short-circuit on falsy.",
        "1. Evaluate ''. 2. Falsy. 3. Return ''.",
        "No evaluation of 'hello'.",
        "Guarding string concatenation.",
        "Whitespace ' ' is truthy.",
        "String operands.",
        "'' or 'default' -> 'default'.",
        "Use if s: for clarity.",
    ),
    (
        "Non-empty strings 'hello' and 'world' — both truthy; and returns last.",
        "Result 'world'.",
        "and returns last truthy when all truthy.",
        "1. 'hello' truthy. 2. 'world' truthy. 3. 'world'.",
        "Useful for picking last configured string in chain.",
        "Different from string concatenation.",
        "Both evaluated.",
        "Compare to 'hello' + 'world'.",
        "Readable code avoids obscure and chains.",
        "Prefer explicit if/else when side effects or logging belong in branches.",
    ),
    (
        "Compound bool: 5>3 True and 10>5 True — overall True.",
        "Both comparisons must hold.",
        "and of two booleans.",
        "1. Evaluate 5>3. 2. Evaluate 10>5. 3. True.",
        "Comparisons have higher precedence than and.",
        "Range checks split into two inequalities.",
        "Add parens for readability even if not required.",
        "Two comparisons.",
        "5>3 and 10<5 is False.",
        "Use chained comparisons when middle matches.",
    ),
    (
        "5>10 is False — first conjunct fails.",
        "Short-circuit: second may still evaluate in Python for and with comparisons.",
        "Actually Python evaluates both for bool and and — both sides evaluated.",
        "1. 5>10 False. 2. and False.",
        "False and anything is False.",
        "Failed multi-criteria gate.",
        "Short-circuit skips right if left falsy for and.",
        "0 and 1 skips 1.",
        "5>3 and 10<5 False.",
        "Use all() for many predicates.",
    ),
    (
        "5>3 True or 10<5 False — first True makes or True.",
        "or short-circuits after first True.",
        "Second operand may not be evaluated if first True.",
        "1. 5>3 True. 2. or True.",
        "or stops at first truthy.",
        "Either criterion enough.",
        "10<5 evaluated only if first False in CPython for or.",
        "Short-circuit.",
        "False or True -> True.",
        "Use any() for iterable.",
    ),
    (
        "5>10 False or 10<5 False — both False.",
        "or needs any True.",
        "Neither comparison holds.",
        "1. First False. 2. Second False. 3. False.",
        "or of two booleans.",
        "No route matched.",
        "Both sides evaluated if first falsy.",
        "Two checks.",
        "True or False -> True.",
        "Consider XOR for exclusive or — not built-in.",
    ),
    (
        "not (5>10) — inner False, not True.",
        "Parentheses force comparison before not.",
        "5>10 is False; not False is True.",
        "1. 5>10 False. 2. not True.",
        "not applies to bool result.",
        "Negating a failed check.",
        "not 5>10 without parens is parse error — not binds to 5.",
        "Trivial.",
        "not (a == b) vs a != b similar for bools.",
        "Keep parens for clarity.",
    ),
    (
        "not (5>3) — inner True, not False.",
        "5>3 is True; negation False.",
        "Successful check negated.",
        "1. 5>3 True. 2. not False.",
        "Use when inverting pass condition.",
        "Testing failure paths.",
        "not on non-bool uses truthiness.",
        "Trivial.",
        "De Morgan: not (a and b).",
        "Prefer explicit inequality when clearer.",
    ),
    (
        "5>3 True and not(10<5) — second is not False True.",
        "10<5 False; not False True.",
        "Both conjuncts True.",
        "1. Left True. 2. not False True. 3. and True.",
        "not binds tighter than and.",
        "Combining threshold with negated failure.",
        "Nested nots confuse — refactor.",
        "Two booleans.",
        "Use variable names for subexpressions.",
        "PEP 8 line continuation for long lines.",
    ),
    (
        "or combines membership and comparison: 5 in list is False, so evaluate 10>5 True.",
        "or True if first truthy — here first is False.",
        "1. 5 in [1,2,3] False. 2. 10>5 True. 3. True.",
        "in has lower precedence than comparisons — check order.",
        "Parentheses clarify mixed expressions.",
        "Fallback route when primary fails.",
        "Short-circuit: second may run after first False.",
        "or evaluates until truthy.",
        "5 in [5] or False -> True.",
        "any([cond1, cond2]) similar.",
    ),
    (
        "and requires both: 5 in [1,2,3] False stops the conjunction.",
        "First False makes entire and False.",
        "10>5 not needed for result — short-circuit.",
        "1. in False. 2. and False.",
        "Second operand may not be evaluated.",
        "Strict multi-check.",
        "If first True, second still evaluated.",
        "Short-circuit and.",
        "all([cond1, cond2]) similar.",
        "Use explicit if for side effects.",
    ),
    (
        "Compares two booleans: (5>3)True and (10>5)True — equality True.",
        "== between two bools checks value equality.",
        "True == True.",
        "1. Left True. 2. Right True. 3. == True.",
        "Parentheses force comparison before ==.",
        "Asserting two predicates agree.",
        "True == 1 is True — bool subclass.",
        "Trivial.",
        "is True vs == True differ for identity.",
        "Use is for singletons only.",
    ),
]


def tail_for(q: str) -> str:
    q = q.strip()
    if q not in QUESTIONS:
        raise ValueError(f"extend tail_for: unknown question {q!r}")
    i = QUESTIONS.index(q)
    return _tail(*TAIL_ROWS[i])


def main() -> None:
    path = Path(__file__).resolve().parents[1] / "src/data/questions/level3.ts"
    text = path.read_text(encoding="utf-8")
    if text.count(BLOCK_START) != len(QUESTIONS):
        raise SystemExit(
            f"Expected {len(QUESTIONS)} generic blocks in level3.ts, found {text.count(BLOCK_START)}"
        )
    tails = [tail_for(q) for q in QUESTIONS]
    out = text
    for tail in tails:
        replacement = tail
        idx = out.find(BLOCK_START)
        if idx == -1:
            raise SystemExit("BLOCK_START not found")
        end = out.find(BLOCK_END, idx)
        if end == -1:
            raise SystemExit("BLOCK_END not found")
        end += len(BLOCK_END)
        out = out[:idx] + replacement + out[end:]
    if BLOCK_START in out:
        raise SystemExit("Not all blocks replaced")
    path.write_text(out, encoding="utf-8")
    print(f"OK: patched {len(tails)} blocks in {path}")


if __name__ == "__main__":
    main()
