#!/usr/bin/env python3
"""
Replace duplicated generic tails in level3_expert_b.ts (50 occurrences).
replacement = "Key Distinctions:\n" + tail
BLOCK_END = Level 3 PEP 8 Notes (same as level3.ts).
No backticks inside tails (TS template literal safety).
"""
from __future__ import annotations

from pathlib import Path

BLOCK_START = (
    "Key Concepts:\n"
    "• See the key concepts and explanation above for the main ideas and bullet points.\n\n"
    "Key Distinctions:"
)

BLOCK_END = (
    "Notes:\n"
    "• Follow PEP 8 and best practices; refer to the official docs for full details."
)

TAILS: list[str] = [

    "• float('nan') is NaN; bool(nan) is True in Python because NaN is a non-zero float object.\n• Use math.isnan(x), not x == float('nan'), to detect NaN.\n\nHow It Works:\n• float.__bool__ treats any nonzero magnitude as true; NaN is nonzero.\n\nStep-by-Step Execution:\n1. Create nan. 2. Call bool. 3. Observe True.\n\nOrder of Operations:\n• bool on float follows numeric magnitude rules, not IEEE total-order rules.\n\nCommon Use Cases:\n• Sanity-checking calculations that should never produce NaN.\n\nEdge Cases:\n• NaN != NaN — reflexivity fails; sorting can misbehave without keys.\n\nPerformance Considerations:\n• Constant-time.\n\nExamples:\n• math.isnan(float('nan')) -> True.\n\nNotes:\n• Prefer pandas.isna for tabular data; handle NaN explicitly in plots."
,
    "• float('inf') is infinite positive float; bool is True (non-zero).\n• inf compares greater than any finite float; use math.isinf for explicit tests.\n\nHow It Works:\n• Same truthiness rule applies to sign of infinity.\n\nStep-by-Step Execution:\n1. Parse inf. 2. bool True.\n\nOrder of Operations:\n• Sign of infinity does not flip truthiness.\n\nCommon Use Cases:\n• Overflow results and limiting behavior in simulations.\n\nEdge Cases:\n• inf + (-inf) yields nan — different truthiness.\n\nPerformance Considerations:\n• Trivial.\n\nExamples:\n• math.isinf(x) and math.copysign(1, x) for sign.\n\nNotes:\n• Watch inf propagation in products and sums."
,
    "• float('-inf') is nonzero; bool True.\n• -inf sorts below all finite numbers.\n\nHow It Works:\n• Magnitude-based bool, not sign-based falsity.\n\nStep-by-Step Execution:\n1. Build -inf. 2. bool True.\n\nOrder of Operations:\n• Unordered comparisons with nan still possible — not this quiz.\n\nCommon Use Cases:\n• Optimization and physics-style asymptotics.\n\nEdge Cases:\n• Comparing -inf with nan is False — partial order.\n\nPerformance Considerations:\n• Trivial.\n\nExamples:\n• math.isinf distinguishes signed infinities.\n\nNotes:\n• Plotting asymptotes and clipped ranges."
,
    '• 0.0 is numerically zero; bool(0.0) is False like int 0.\n• Contrast with any nonzero float, including subnormal tiny values (usually True).\n\nHow It Works:\n• float shares falsy zero with int.\n\nStep-by-Step Execution:\n1. Literal 0.0. 2. bool False.\n\nOrder of Operations:\n• Magnitude zero means falsy for numbers.\n\nCommon Use Cases:\n• Default metrics and uninitialized gauges.\n\nEdge Cases:\n• -0.0 still compares equal to 0.0; bool still False.\n\nPerformance Considerations:\n• Trivial.\n\nExamples:\n• math.copysign(1, -0.0) reveals signed zero.\n\nNotes:\n• Use isclose for residuals near zero, not raw truth tests.'
,
    '• IEEE -0.0 equals +0.0; bool(-0.0) is False.\n• Sign of zero can matter for 1/x but not for truthiness.\n\nHow It Works:\n• Same as +0.0 for boolean context.\n\nStep-by-Step Execution:\n1. Construct -0.0. 2. bool False.\n\nOrder of Operations:\n• Signed-zero edge cases in numerical libraries.\n\nCommon Use Cases:\n• 1 / -0.0 is -inf — unrelated to bool.\n\nEdge Cases:\n• Trivial.\n\nPerformance Considerations:\n• struct.unpack may reveal sign bit — rare in app code.\n\nExamples:\n• Do not branch on signed zero in business logic without domain reason.\n\nNotes:\n• Reserve signed-zero handling for numeric libraries, not UI booleans.'
,
    "• Non-empty string '0' has length 1; bool is True — the digit character is not numeric zero.\n• Only the empty string '' is falsy among str (plus whitespace-only policy varies by use).\n\nHow It Works:\n• Truthiness uses emptiness, not numeric parsing.\n\nStep-by-Step Execution:\n1. str '0'. 2. bool True.\n\nOrder of Operations:\n• str never auto-parses to int in truth tests.\n\nCommon Use Cases:\n• CLI arguments and form fields before int().\n\nEdge Cases:\n• Whitespace ' ' is truthy; strip before checks if needed.\n\nPerformance Considerations:\n• O(1) length.\n\nExamples:\n• int('0') == 0 but '0' itself is truthy.\n\nNotes:\n• Validate with explicit int() and try/except."
,
    "• The string 'False' is non-empty, so bool is True — it is not the bool singleton False.\n• Lexical text does not auto-convert to bool in truth tests.\n\nHow It Works:\n• Need ast.literal_eval or custom parsing for 'True'/'False' strings.\n\nStep-by-Step Execution:\n1. Non-empty str. 2. bool True.\n\nOrder of Operations:\n• Config parsers differ from bare truth checks.\n\nCommon Use Cases:\n• Feature flags read from text files.\n\nEdge Cases:\n• distutils.util.strtobool maps common strings — different API.\n\nPerformance Considerations:\n• Trivial.\n\nExamples:\n• json.loads maps JSON false to False — not plain str.\n\nNotes:\n• Document expected string tokens for settings."
,
    "• The string 'None' is truthy — five characters — not the None singleton.\n• None object is falsy; the text 'None' is a normal nonempty string.\n\nHow It Works:\n• Never use truthiness to detect None — use is None.\n\nStep-by-Step Execution:\n1. str object. 2. bool True.\n\nOrder of Operations:\n• Serialization and logging often stringify None accidentally.\n\nCommon Use Cases:\n• JSON null becomes None in json.loads — distinct from 'None' str.\n\nEdge Cases:\n• APIs that echo None as text can confuse clients expecting JSON null.\n\nPerformance Considerations:\n• Trivial.\n\nExamples:\n• if x is None: is the idiomatic guard.\n\nNotes:\n• Teach beginners the string-vs-None confusion early."
,
    '• List [0] is nonempty; bool([0]) is True even though 0 is falsy.\n• Container truthiness uses len, not all(element truth).\n\nHow It Works:\n• list.__bool__ returns False only for empty lists.\n\nStep-by-Step Execution:\n1. len 1. 2. bool True.\n\nOrder of Operations:\n• Contrast all([False]) which is False.\n\nCommon Use Cases:\n• Checking that a list exists before indexing element 0.\n\nEdge Cases:\n• Nested [[]] still truthy at outer level.\n\nPerformance Considerations:\n• O(1) length check.\n\nExamples:\n• if rows: pick rows[0]\n\nNotes:\n• Use all(rows) or any(rows) if element truth matters.'
,
    '• Outer list [[]] has length 1; inner empty list does not falsify the outer container.\n• Emptiness is about the immediate container only.\n\nHow It Works:\n• 1. len 1. 2. bool True.\n\nStep-by-Step Execution:\nTree shapes where parent node exists with empty child.\n\nOrder of Operations:\n• Matrix rows with placeholder empty rows.\n\nCommon Use Cases:\n• Deeply nested empties can still yield truthy outer wrappers.\n\nEdge Cases:\n• Constant-time.\n\nPerformance Considerations:\n• Flatten or check inner structure explicitly when needed.\n\nExamples:\n• Combine with any() on children for meaningful emptiness.\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• Tuple (0,) has length 1 — truthy — trailing comma makes a tuple, not int.\n• Without comma, (0) is int 0 which is falsy — easy typo.\n\nHow It Works:\n• Container truthiness from length.\n\nStep-by-Step Execution:\n1. Tuple one slot. 2. bool True.\n\nOrder of Operations:\n• Fixed-arity records that may hold zero magnitudes.\n\nCommon Use Cases:\n• Contrast (0) which parses as int.\n\nEdge Cases:\n• O(1).\n\nPerformance Considerations:\n• x = (0,) vs x = (0) — review reviews carefully.\n\nExamples:\n• NamedTuple for clarity in APIs.\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    "• Dict {0:0} has one entry; bool is True — key count matters, not value truthiness.\n• Empty dict only is falsy.\n\nHow It Works:\n• 1. len>0. 2. bool True.\n\nStep-by-Step Execution:\ndict.__bool__ uses size.\n\nOrder of Operations:\n• Configuration dicts with zero values.\n\nCommon Use Cases:\n• Keys False and 0 collide — separate question.\n\nEdge Cases:\n• O(1) size.\n\nPerformance Considerations:\n• if settings: before iterating keys.\n\nExamples:\n• Use .get and 'in' for presence, not truth of dict.\n\nNotes:\n• — (Editorial: expand this slot if needed.)"
,
    '• frozenset() is empty; bool False — same emptiness rule as set().\n• Immutable set type follows set truthiness.\n\nHow It Works:\n• 1. len 0. 2. bool False.\n\nStep-by-Step Execution:\nOptional tag sets before items added.\n\nOrder of Operations:\n• frozenset({0}) becomes truthy.\n\nCommon Use Cases:\n• Trivial.\n\nEdge Cases:\n• if tags: process(tags)\n\nPerformance Considerations:\n• Empty frozenset is a singleton-like useful sentinel container.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• frozenset({0}) has one element; bool True even though element is 0.\n• Set truthiness is about cardinality, not member truthiness.\n\nHow It Works:\n• 1. len 1. 2. bool True.\n\nStep-by-Step Execution:\nFrozen tag sets with numeric zero as token.\n\nOrder of Operations:\n• Empty set remains falsy.\n\nCommon Use Cases:\n• O(1) length.\n\nEdge Cases:\n• len({0, False}) == 1 due to key equality.\n\nPerformance Considerations:\n• Prefer str tags if collisions confuse readers.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    "• bytearray() has length 0; bool False — buffer emptiness.\n• Like bytes/list, length drives truthiness.\n\nHow It Works:\n• 1. No bytes. 2. bool False.\n\nStep-by-Step Execution:\nBinary parsers starting empty then extending.\n\nOrder of Operations:\n• bytearray(b'\\x00') length 1 is truthy.\n\nCommon Use Cases:\n• O(1).\n\nEdge Cases:\n• if buf: send(buf)\n\nPerformance Considerations:\n• memoryview truthiness follows underlying length.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)"
,
    "• bytearray(b'\\x00') length 1; bool True — NUL byte is still data.\n• Zero-valued byte is not container emptiness.\n\nHow It Works:\n• 1. len 1. 2. bool True.\n\nStep-by-Step Execution:\nBinary frames with padding bytes.\n\nOrder of Operations:\n• Empty bytearray remains the only falsy buffer here.\n\nCommon Use Cases:\n• Linear truthiness O(1).\n\nEdge Cases:\n• if data: checksum(data)\n\nPerformance Considerations:\n• Distinguish empty buffer from buffer of zeros.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)"
,
    '• range(0) is empty; bool False — no iterations.\n• range truthiness reflects whether any integer would be produced.\n\nHow It Works:\n• 1. len-like 0. 2. False.\n\nStep-by-Step Execution:\nGuard for loops when upper bound may be 0.\n\nOrder of Operations:\n• range(1) truthy.\n\nCommon Use Cases:\n• O(1) __bool__.\n\nEdge Cases:\n• Prefer explicit n > 0 over bool(range(n)) for readers.\n\nPerformance Considerations:\n• Huge stop values still cheap for truth test.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• range(1) yields one value; bool True.\n• Any positive-length arithmetic range is truthy.\n\nHow It Works:\n• 1. Count >0. 2. True.\n\nStep-by-Step Execution:\nTeaching bounds for loops.\n\nOrder of Operations:\n• range(0,0,step) empty — falsy.\n\nCommon Use Cases:\n• O(1).\n\nEdge Cases:\n• len(range(a,b)) formula for counts.\n\nPerformance Considerations:\n• Avoid materializing range as list for truthiness.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• object() instances are truthy by default — no __bool__ making them false.\n• Bare object is a common unique sentinel when identity matters.\n\nHow It Works:\n• 1. Allocate. 2. bool True.\n\nStep-by-Step Execution:\nCustom singletons subclassing object.\n\nOrder of Operations:\n• Could override __bool__ in subclasses — not here.\n\nCommon Use Cases:\n• O(1).\n\nEdge Cases:\n• sentinel = object()\n\nPerformance Considerations:\n• Enum or None often clearer for public APIs.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    "• or scans left to right and returns the first truthy operand — here the string 'found!' after falsy sentinels.\n• None, 0, '', [] are falsy; the string at the end is truthy.\n\nHow It Works:\n• Short-circuit stops at first truthy.\n\nStep-by-Step Execution:\n1. Test None — falsy. 2. Continue until 'found!'.\n\nOrder of Operations:\n• Default and fallback chains in configuration.\n\nCommon Use Cases:\n• If every operand were falsy, or returns the last value — not this chain.\n\nEdge Cases:\n• Evaluates until success.\n\nPerformance Considerations:\n• cfg.get('x') or default — similar pattern.\n\nExamples:\n• Beware skipping valid numeric 0 with or — use explicit None tests.\n\nNotes:\n• — (Editorial: expand this slot if needed.)"
,
    '• bool subclasses int; True+True+True evaluates as 1+1+1 == 3 in arithmetic contexts.\n• PEP 285 made bool a subclass of int for backward compatibility.\n\nHow It Works:\n• 1. Promote True to 1. 2. Sum.\n\nStep-by-Step Execution:\nAddition is left-associative.\n\nOrder of Operations:\n• Counting True values via sum on a list of bools.\n\nCommon Use Cases:\n• numpy bool dtypes behave differently — mind arrays.\n\nEdge Cases:\n• Tiny integer ops.\n\nPerformance Considerations:\n• sum([True, False, True]) -> 2\n\nExamples:\n• Prefer explicit int(x) in APIs returning counts.\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• True*10 promotes True to 1; product is 10.\n• Multiplication uses numeric promotion, not string repetition.\n\nHow It Works:\n• 1. 1*10.\n\nStep-by-Step Execution:\nArithmetic with bools is usually style-smell outside teaching.\n\nOrder of Operations:\n• Bitmask tutorials sometimes abuse this.\n\nCommon Use Cases:\n• False times anything int-like gives 0.\n\nEdge Cases:\n• O(1).\n\nPerformance Considerations:\n• 10 * True == 10\n\nExamples:\n• Use int(flag) when you mean 0/1.\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• False**0 follows numeric exponent rules; 0**0 is 1 in Python integers.\n• False acts as integer 0 in power.\n\nHow It Works:\n• 1. Compute 0**0 -> 1.\n\nStep-by-Step Execution:\n** binds tighter than unary operators in many contexts — mind parentheses.\n\nOrder of Operations:\n• Puzzle code, not typical production.\n\nCommon Use Cases:\n• Debate about 0**0 in math does not change Python int result here.\n\nEdge Cases:\n• Constant-time.\n\nPerformance Considerations:\n• True**0 is also 1.\n\nExamples:\n• Use pow with three arguments for modular exponentiation in crypto.\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• True == 1 is True — value equality with bool subclassing int.\n• == compares values; it is not identity.\n\nHow It Works:\n• 1. Coerce bool and int under equality.\n\nStep-by-Step Execution:\nJSON true maps to True naturally.\n\nOrder of Operations:\n• True == 2 is False.\n\nCommon Use Cases:\n• Trivial.\n\nEdge Cases:\n• hash(True) == hash(1) — dict key collision risk.\n\nPerformance Considerations:\n• Use is True only when singleton semantics matter.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• True is 1 is False — different objects despite == True.\n• is compares identity (id).\n\nHow It Works:\n• 1. id(True) != id(1).\n\nStep-by-Step Execution:\nTeach equality vs identity side by side.\n\nOrder of Operations:\n• Small int caching is separate mechanism.\n\nCommon Use Cases:\n• Pointer compare.\n\nEdge Cases:\n• True is True is True.\n\nPerformance Considerations:\n• Never write True is 1 in production style guides.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• False == 0 is True — bool and int zero compare equal under ==.\n• Same mechanism as True/1.\n\nHow It Works:\n• 1. Equality succeeds.\n\nStep-by-Step Execution:\nJSON false mapping.\n\nOrder of Operations:\n• False == 0.0 is also True.\n\nCommon Use Cases:\n• Trivial.\n\nEdge Cases:\n• hash(False) == hash(0) — dict key collision.\n\nPerformance Considerations:\n• Use explicit key types to avoid surprise merges.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• False == 0.0 is True — numeric equality across int and float zero.\n• IEEE zero compares equal to int zero under ==.\n\nHow It Works:\n• 1. Compare across types.\n\nStep-by-Step Execution:\nScientific code comparing magnitudes.\n\nOrder of Operations:\n• NaN would break reflexivity — not this case.\n\nCommon Use Cases:\n• Trivial.\n\nEdge Cases:\n• math.isclose for approximate floats.\n\nPerformance Considerations:\n• Dict keys 0 and 0.0 collide.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    "• False == '' is False — bool and empty str are incomparable for equality meaningfully here.\n• No implicit '' to False conversion under ==.\n\nHow It Works:\n• 1. Compare distinct types.\n\nStep-by-Step Execution:\nAvoid mixing bool and str in equality.\n\nOrder of Operations:\n• '' == 0 is also False.\n\nCommon Use Cases:\n• Trivial.\n\nEdge Cases:\n• Use if not s: for empty string checks.\n\nPerformance Considerations:\n• Validate user input with explicit rules.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)"
,
    "• Dict {True:'a', 1:'b'} merges keys True and 1 — equal hashes and equality — last wins.\n• Effective single entry: key 1 maps to 'b' (or True — same slot).\n\nHow It Works:\n• 1. Insert True. 2. Insert 1 — collision.\n\nStep-by-Step Execution:\nSurprising dict length for beginners.\n\nOrder of Operations:\n• Use str keys when mixing bool-like and int-like tokens.\n\nCommon Use Cases:\n• 1.0 also equals 1 — triple collision possible.\n\nEdge Cases:\n• O(1) inserts.\n\nPerformance Considerations:\n• len({True:1, 1:2}) == 1\n\nExamples:\n• Prefer Enum or str keys in public schemas.\n\nNotes:\n• — (Editorial: expand this slot if needed.)"
,
    "• Keys 0 and False collide like 1/True — one entry remains.\n• hash and equality alignment for dict keys.\n\nHow It Works:\n• 1. Build dict. 2. Observe single slot.\n\nStep-by-Step Execution:\nConfiguration merging bugs.\n\nOrder of Operations:\n• Similar caution for 0.0.\n\nCommon Use Cases:\n• Constant.\n\nEdge Cases:\n• {0:'a', False:'b'} -> one key\n\nPerformance Considerations:\n• Explicit string keys for human-readable maps.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)"
,
    "• [True,1,1.0].count(True) uses == — three values equal True, so count is 3.\n• count is equality-based, not identity-based.\n\nHow It Works:\n• 1. Compare each element to True.\n\nStep-by-Step Execution:\nSurprising when mixing numeric forms.\n\nOrder of Operations:\n• NaN would not compare equal to itself — different behavior.\n\nCommon Use Cases:\n• O(n) scan.\n\nEdge Cases:\n• sum(1 for x in lst if x is True) for identity-specific counting.\n\nPerformance Considerations:\n• Document what 'sameness' means in analytics.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)"
,
    '• Set {True,1,1.0} collapses to one element — equality merges members.\n• Set requires consistent hash/equality.\n\nHow It Works:\n• 1. Insert True; 1 and 1.0 deduplicate.\n\nStep-by-Step Execution:\nUnique collections with numeric/bool confusion.\n\nOrder of Operations:\n• len is 1.\n\nCommon Use Cases:\n• O(n) inserts average.\n\nEdge Cases:\n• Use homogeneous element types in sets when teaching.\n\nPerformance Considerations:\n• frozenset for dict keys with similar caution.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• sorted([None, 1]) raises TypeError in Python 3 — None and int are not orderable.\n• sorting requires total ordering compatible with < between elements.\n\nHow It Works:\n• 1. sort tries less-than. 2. TypeError.\n\nStep-by-Step Execution:\nUse key= mapping None to a sentinel tuple.\n\nOrder of Operations:\n• Migration from Python 2 ordering differences.\n\nCommon Use Cases:\n• N/A — error path.\n\nEdge Cases:\n• sorted(items, key=lambda x: (x is None, x))\n\nPerformance Considerations:\n• numpy sorts may coerce — different ecosystem.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• None < 0 raises TypeError — no natural ordering between NoneType and int.\n• Rich comparisons return NotImplemented or error across these types.\n\nHow It Works:\n• 1. Attempt comparison. 2. Error.\n\nStep-by-Step Execution:\nNever order None against numbers.\n\nOrder of Operations:\n• Use explicit is None checks.\n\nCommon Use Cases:\n• functools.cmp_to_key is legacy style.\n\nEdge Cases:\n• Fails immediately.\n\nPerformance Considerations:\n• SQL NULL semantics differ — ORMs map carefully.\n\nExamples:\n• Optional[int] typing reflects possibility of None.\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• None == 0 is False — None equals only None.\n• No coercion of None to numeric zero under ==.\n\nHow It Works:\n• 1. Equality fails.\n\nStep-by-Step Execution:\nDefault handling with explicit None tests.\n\nOrder of Operations:\n• None == False is also False.\n\nCommon Use Cases:\n• Trivial.\n\nEdge Cases:\n• if x is None:\n\nPerformance Considerations:\n• Database NULL is tri-state — do not mirror Python None blindly.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• x or [1,2] with x=[] chooses the right side because empty list is falsy.\n• or returns first truthy or last operand if all falsy.\n\nHow It Works:\n• 1. [] falsy. 2. Evaluate [1,2].\n\nStep-by-Step Execution:\nDefaulting mutable list — copy if you must avoid shared mutation.\n\nOrder of Operations:\n• If x were truthy, same object returned — identity preserved.\n\nCommon Use Cases:\n• O(1) selection.\n\nEdge Cases:\n• y = x if x else [1,2] reads clearly.\n\nPerformance Considerations:\n• Do not use [] as default arg — use None pattern.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• x=[3] is truthy; x or [1,2] returns x without building default.\n• Short-circuit stops at first truthy.\n\nHow It Works:\n• 1. x truthy. 2. Return x.\n\nStep-by-Step Execution:\nOptional parameters with user-supplied nonempty list.\n\nOrder of Operations:\n• Mutating result mutates original — same object.\n\nCommon Use Cases:\n• Identity return.\n\nEdge Cases:\n• if x is None: x = default — different from empty list semantics.\n\nPerformance Considerations:\n• Clarify whether empty list should trigger default.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• Chained a == b == c with all zeros: each pairwise equality holds — True.\n• Equivalent to (a==b) and (b==c) with b evaluated once in chaining.\n\nHow It Works:\n• 1. 0==0 and 0==0.\n\nStep-by-Step Execution:\nAsserting three tied variables.\n\nOrder of Operations:\n• NaN breaks transitivity — not with ints.\n\nCommon Use Cases:\n• Two == operations.\n\nEdge Cases:\n• a==b==c is clearer than nested and for readers.\n\nPerformance Considerations:\n• Use math.isclose for floats.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• 1 != 2 != 1 parses as (1!=2) and (2!=1) — both true — overall True.\n• Chained inequality is not the same as comparing all three pairwise in one hop.\n\nHow It Works:\n• 1. First pair true. 2. Second pair true.\n\nStep-by-Step Execution:\nPuzzle illustrating chained comparisons.\n\nOrder of Operations:\n• 1!=2!=2 would fail second segment.\n\nCommon Use Cases:\n• Two comparisons.\n\nEdge Cases:\n• Draw small truth tables for teaching.\n\nPerformance Considerations:\n• Read language reference on chained comparisons.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• Dict comprehension keeps odd i with i%2 truthy: {1:1, 3:9} from range(5).\n• if i%2 filters evens — zero is falsy.\n\nHow It Works:\n• 1. Loop i. 2. Filter odds. 3. Square values.\n\nStep-by-Step Execution:\nCombining filter with mapping in one comprehension.\n\nOrder of Operations:\n• Could write i%2==1 explicitly.\n\nCommon Use Cases:\n• O(n).\n\nEdge Cases:\n• {i:i**2 for i in range(5) if i%2==1}\n\nPerformance Considerations:\n• Walrus can name parity once in larger expressions.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    "• all(map(str.isdigit, '12345')) — every char is digit — True.\n• all consumes the iterator from map; short-circuits on first False.\n\nHow It Works:\n• 1. Each char isdigit. 2. True.\n\nStep-by-Step Execution:\nValidating numeric strings before int().\n\nOrder of Operations:\n• Empty string: all([]) vacuously True — watch separately.\n\nCommon Use Cases:\n• O(n) length.\n\nEdge Cases:\n• s.isdigit() on whole string may differ for signs/+.\n\nPerformance Considerations:\n• regex ^\\d+$ for whole-string match.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)"
,
    "• any(map(str.isdigit, 'abc1')) finds a digit — True.\n• any stops at first True — lazy evaluation from map.\n\nHow It Works:\n• 1. Scan until '1'.\n\nStep-by-Step Execution:\nPassword has-digit checks.\n\nOrder of Operations:\n• any([]) is False.\n\nCommon Use Cases:\n• Short-circuit may skip tail of string.\n\nEdge Cases:\n• any(c.isdigit() for c in s) equivalent.\n\nPerformance Considerations:\n• Use regex for category rules beyond one digit.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)"
,
    "• all(map(str.isdigit, 'abc')) — no digits — False.\n• First nondigit short-circuits all.\n\nHow It Works:\n• 1. 'a' fails isdigit.\n\nStep-by-Step Execution:\nRejecting non-numeric codes.\n\nOrder of Operations:\n• Vacuous all on empty iterable is True — edge case.\n\nCommon Use Cases:\n• O(n) until failure.\n\nEdge Cases:\n• isalnum vs isdigit distinction.\n\nPerformance Considerations:\n• Unicode digits may need normalization.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)"
,
    '• List comp [x if x>0 else -x for x in [-1,2,-3]] maps to absolute values [1,2,3].\n• Conditional expression in output expression position.\n\nHow It Works:\n• 1. Bind each x. 2. Apply abs-like ternary.\n\nStep-by-Step Execution:\nPrefer built-in abs(x) for clarity in real code.\n\nOrder of Operations:\n• Nested conditionals reduce readability.\n\nCommon Use Cases:\n• O(n).\n\nEdge Cases:\n• [abs(x) for x in lst]\n\nPerformance Considerations:\n• Walrus if computing expensive transform once.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• next((x for x in [5,3,8,1] if x>6), None) returns 8 — first match.\n• Generator expression finds first satisfying predicate; default None if none.\n\nHow It Works:\n• 1. Iterate. 2. Yield first >6.\n\nStep-by-Step Execution:\nSearch without building a list.\n\nOrder of Operations:\n• If no match, next returns default — here 8 exists.\n\nCommon Use Cases:\n• Short-circuit scan.\n\nEdge Cases:\n• next(..., None) for optional earliest match.\n\nPerformance Considerations:\n• Explicit for-loop often clearer for debugging.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• No x>6 in [5,3,1] — generator exhausted; next returns default None.\n• Short-circuit never finds a truthy predicate.\n\nHow It Works:\n• 1. Scan all. 2. Return default.\n\nStep-by-Step Execution:\nContrasts with finding a match.\n\nOrder of Operations:\n• Distinguish None default from valid None data with care.\n\nCommon Use Cases:\n• O(n) full pass.\n\nEdge Cases:\n• for x in data: if x>6: return x; return None\n\nPerformance Considerations:\n• Use a sentinel other than None if None is valid data.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• all(isinstance(x,int) for x in [1,True,3]) is True — bool is subclass of int.\n• isinstance(True, int) succeeds — separate bool if you need to exclude.\n\nHow It Works:\n• 1. Each element passes int check.\n\nStep-by-Step Execution:\nType-guarding heterogeneous lists.\n\nOrder of Operations:\n• type(x) is int excludes bool — different test.\n\nCommon Use Cases:\n• O(n).\n\nEdge Cases:\n• Use Union types in typing when bool should be distinct.\n\nPerformance Considerations:\n• Protocol and ABC checks for duck typing.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• any(x is None for x in [1,None,3]) finds None — True.\n• Generator uses identity check for sentinel.\n\nHow It Works:\n• 1. Second element matches.\n\nStep-by-Step Execution:\nOptional row validation.\n\nOrder of Operations:\n• x==None discouraged — any uses is.\n\nCommon Use Cases:\n• Short-circuit True.\n\nEdge Cases:\n• if any(v is None for v in row): error\n\nPerformance Considerations:\n• pandas isna for tabular None/NaN.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• sum(x>0 for x in [-1,2,-3,4]) counts positives — bools sum as 0/1 — result 2.\n• Generator yields True/False; sum coerces to int addition.\n\nHow It Works:\n• 1. Count truths.\n\nStep-by-Step Execution:\nInline counting without list of flags.\n\nOrder of Operations:\n• sum starts at 0.\n\nCommon Use Cases:\n• O(n).\n\nEdge Cases:\n• len([x for x in a if x>0]) materializes — more memory.\n\nPerformance Considerations:\n• numpy.count_nonzero for large arrays.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
,
    '• max(range(10), key=lambda x: -(x-5)**2) selects x maximizing a concave quadratic — peak at 5.\n• key= transforms items before comparison; max picks one argmax.\n\nHow It Works:\n• 1. Evaluate key for each candidate. 2. Take argmax.\n\nStep-by-Step Execution:\nTies: first maximal item wins in CPython max stability.\n\nOrder of Operations:\n• Simple demo of key= without sorting entire range.\n\nCommon Use Cases:\n• O(n) over iterable.\n\nEdge Cases:\n• numpy.argmax for vectorized data.\n\nPerformance Considerations:\n• Prefer readable names for key functions in production.\n\nExamples:\n• — (Editorial: expand this slot if needed.)\n\nNotes:\n• — (Editorial: expand this slot if needed.)'
]


def main() -> None:
    path = Path(__file__).resolve().parents[1] / "src/data/questions/level3_expert_b.ts"
    text = path.read_text(encoding="utf-8")
    if text.count(BLOCK_START) != len(TAILS):
        raise SystemExit(f"Expected {len(TAILS)} blocks, found {text.count(BLOCK_START)}")
    out = text
    for tail in TAILS:
        replacement = "Key Distinctions:\n" + tail
        idx = out.find(BLOCK_START)
        if idx == -1:
            raise SystemExit("BLOCK_START not found")
        end = out.find(BLOCK_END, idx)
        if end == -1:
            raise SystemExit("BLOCK_END not found")
        end += len(BLOCK_END)
        out = out[:idx] + replacement + out[end:]
    if BLOCK_START in out:
        raise SystemExit("Not all blocks replaced")
    path.write_text(out, encoding="utf-8")
    print(f"OK: patched {len(TAILS)} blocks in {path}")


if __name__ == "__main__":
    main()
