// Paste into SHORT_EXPLANATIONS_FR in shortExplanationsTranslations.ts

  2751: "Décorateur qui renvoie la fonction inchangée.",
  2752: "Le décorateur encapsule la fonction dans une autre fonction.",
  2753: "Le wrapper du décorateur préserve les arguments de la fonction.",
  2754: "@wraps préserve les métadonnées originales de la fonction.",
  2755: "Usine à décorateurs : fonction qui renvoie un décorateur.",
  2756: "Décorateur basé sur une classe utilisant __call__.",
  2757: "@staticmethod est un décorateur intégré.",
  2758: "@classmethod est un décorateur intégré.",
  2759: "@property est un décorateur intégré.",
  2760: "Plusieurs décorateurs appliqués de bas en haut.",
  2761: "Patron Singleton : __new__ garantit une seule instance.",
  2762: "Patron Factory : crée des objets sans spécifier la classe exacte.",
  2763: "Patron Observer : le sujet notifie les observateurs des changements.",
  2764: "Patron Strategy : algorithmes interchangeables.",
  2765: "Patron Adapter : adapte l'interface d'une classe à une autre.",
  2766: "Patron Builder : construit des objets complexes étape par étape.",
  2767: "Patron Prototype : crée des objets par clonage.",
  2768: "Patron Facade : fournit une interface simplifiée à un sous-système complexe.",
  2769: "Patron Command : encapsule la requête comme objet.",
  2770: "Patron Composite : traite objets individuels et composites uniformément.",
  2771: "Le paramètre metaclass définit la métaclasse de la classe.",
  2772: "Le __new__ de la métaclasse contrôle la création de la classe.",
  2773: "Le __init__ de la métaclasse peut ajouter des attributs à la classe.",
  2774: "Le __call__ de la métaclasse contrôle la création d'instance.",
  2775: "La métaclasse peut implémenter le patron Singleton.",
  2776: "__slots__ restreint les attributs d'instance.",
  2777: "__slots__ supprime __dict__ (économie de mémoire).",
  2778: "__getattribute__ intercepte tout accès aux attributs.",
  2779: "__getattr__ n'est appelé que si l'attribut n'est pas trouvé.",
  2780: "__setattr__ intercepte toute assignation d'attribut.",
  2781: "PEP 8 est le guide de style Python.",
  2782: "Annotations de type pour paramètres et retour.",
  2783: "Annotations de type avec génériques (List, Dict).",
  2784: "Annotations de type avec valeurs par défaut.",
  2785: "Référence anticipée (chaîne) pour les types.",
  2786: "Annotation de type Optional.",
  2787: "Annotation de type Union.",
  2788: "Annotation de type Callable.",
  2789: "Instance de dataclass avec @dataclass.",
  2790: "collections.Counter compte les occurrences.",
  2791: "collections.defaultdict fournit une valeur par défaut pour les clés absentes.",
  2792: "collections.deque est une file à double extrémité.",
  2793: "itertools.chain enchaîne des itérables.",
  2794: "itertools.cycle crée un itérateur infini.",
  2795: "open() avec 'with' gère la fermeture automatique.",
  2796: "Le module json sérialise et désérialise du JSON.",
  2797: "json.dumps() convertit un objet Python en chaîne JSON.",
  2798: "json.loads() convertit une chaîne JSON en objet Python.",
  2799: "datetime.datetime représente date et heure.",
  2800: "datetime.timedelta représente une durée.",
  2801: "La métaclasse est la classe d'une classe.",
  2802: "__slots__ empêche la création de __dict__ pour économiser la mémoire.",
  2803: "__annotations__ stocke les annotations de type comme dictionnaire.",
  2804: "asyncio.run() exécute une fonction async et renvoie le résultat.",
  2805: "Le mode 'r' ouvre un fichier en lecture (mode par défaut de open()).",
  2806: "Le mode 'w' ouvre un fichier en écriture, le crée s'il n'existe pas.",
  2807: "Le mode 'a' ouvre un fichier en ajout — les données sont écrites à la fin.",
  2808: "Le mode 'x' est création exclusive — crée un nouveau fichier ou lève FileExistsError.",
  2809: "Le mode 'rb' ouvre un fichier en lecture binaire, renvoyant des bytes.",
  2810: "f.read() lit tout le fichier et renvoie le contenu comme une chaîne.",
  2811: "readline() lit une seule ligne du fichier, incluant le saut de ligne.",
  2812: "readlines() renvoie une liste de toutes les lignes du fichier.",
  2813: "write() renvoie le nombre de caractères (ou bytes en mode binaire) écrits.",
  2814: "writelines() écrit chaque chaîne telle quelle — n'ajoute pas de saut de ligne.",
  2815: "Le bloc with assure que le fichier est correctement fermé à la sortie.",
  2816: "seek(0) repositionne le pointeur de fichier au début.",
  2817: "tell() renvoie la position actuelle du pointeur de fichier (entier).",
  2818: "f.closed est un attribut booléen True si le fichier a été fermé.",
  2819: "Spécifier encoding assure UTF-8 pour la lecture/écriture.",
  2820: "Le mode par défaut de open() est 'r' (lecture en mode texte).",
  2821: "Les objets fichier sont itérables — on peut les parcourir avec for.",
  2822: "truncate() tronque la taille du fichier. Sans argument, tronque à la position actuelle.",
  2823: "date.today() renvoie la date du jour comme objet datetime.date.",
  2824: "datetime.now() renvoie la date et l'heure locales courantes.",
  2825: "L'attribut .year d'un objet date renvoie l'année.",
  2826: "L'attribut .month d'un objet date renvoie le mois (1-12).",
  2827: "L'attribut .day d'un objet date renvoie le jour du mois.",
  2828: "L'attribut .hour d'un objet datetime renvoie l'heure (0-23).",
  2829: "L'attribut .minute d'un objet datetime renvoie les minutes.",
  2830: "L'attribut .days d'un timedelta renvoie le nombre de jours.",
  2831: "Ajouter un timedelta de 10 jours au 15 janvier donne le 25 janvier.",
  2832: "Soustraire deux dates donne un timedelta ; .days renvoie la différence.",
  2833: "strftime("%Y-%m-%d") formate une datetime en AAAA-MM-JJ.",
  2834: "strftime("%d/%m/%Y") formate en JJ/MM/AAAA.",
  2835: "strptime analyse une chaîne de date en objet datetime ; .day renvoie le jour.",
  2836: "weekday() renvoie le jour de la semaine (0=lundi, 6=dimanche).",
  2837: "isoformat() renvoie la date en chaîne ISO 8601 : AAAA-MM-JJ.",
  2838: "25 heures = 1 jour + 1 heure. .days renvoie uniquement les jours entiers.",
  2839: "25 heures = 1 jour + 1 heure. .seconds renvoie le reste en secondes.",
  2840: "re.match vérifie au début de la chaîne. \\d+ correspond à un ou plusieurs chiffres.",
  2841: "re.search parcourt toute la chaîne et trouve la première correspondance.",
  2842: "re.match() vérifie seulement au début ; re.search() recherche partout.",
  2843: "re.findall renvoie la liste de toutes les correspondances non chevauchantes.",
  2844: "re.sub remplace chaque correspondance par la chaîne de remplacement.",
  2845: "re.split découpe la chaîne à chaque correspondance du motif.",
  2846: "Le motif ^\\d+$ vérifie si toute la chaîne consiste en un ou plusieurs chiffres.",
  2847: ""123a5" contient la lettre 'a', donc ne correspond pas au motif tout-chiffres.",
  2848: "[aeiou] correspond à une voyelle. Dans "hello world" : e, o, o.",
  2849: "\\b est une frontière de mot, \\w+ correspond à un ou plusieurs caractères de mot.",
  2850: "Les parenthèses créent des groupes de capture. Groupe 1 capture "user".",