/**
 * French translations for option text.
 * Maps question ID -> list of (English, French) option pairs.
 * Generated by script.
 */

export const OPTIONS_FR: Record<number, Record<string, string>> = {
  339: {
    "Yes, with different quote types": "Oui, avec différents types de citations",
  },
  564: {
    "A unique integer identifier": "Un identifiant numérique unique",
    "The object's size in bytes": "La taille de l'objet en octets",
  },
  710: {
    "int gives -3, floor gives -4": "int donne -3, floor donne -4",
    "int gives -4, floor gives -3": "int donne -4, floor donne -3",
  },
  739: {
    "Yes, fsum gives exactly 0.6": "Oui, fsum donne exactement 0,6",
    "No, both give the same result": "Non, les deux donnent le même résultat.",
  },
  804: {
    "Decimal('0.3333333333333333333333333333')": "Décimal('0,3333333333333333333333333333')",
  },
  812: {
    "Decimal('1.414213562373095048801688724')": "Décimal('1,414213562373095048801688724')",
  },
  823: {
    "Fraction(3602879701896397, 36028797018963968)": "Fraction(3602879701896397, 36028797018963968)",
  },
  851: {
    "A tiny number close to 0 (not exactly 0)": "Un nombre minuscule proche de 0 (mais pas exactement égal à 0).",
  },
  858: {
    "Smallest float so that 1.0 + epsilon != 1.0": "Plus petite valeur flottante telle que 1,0 + epsilon != 1,0",
    "The smallest positive float": "Le plus petit flottement positif",
    "Float precision in decimal digits": "Précision des nombres flottants en chiffres décimaux",
  },
  862: {
    "Yes, Python integers have unlimited precision": "Oui, les entiers Python ont une précision illimitée",
  },
  864: {
    "Returns 1e+308 (valid float)": "Renvoie 1e+308 (nombre flottant valide)",
  },
  867: {
    "No, Python computes it exactly": "Non, Python le calcule exactement.",
  },
  930: {
    "== compares values, is compares identity": "== compare les valeurs, is compare l'identité",
  },
  1024: {
    "Returns early to avoid deep nesting": "Retourne tôt pour éviter les nids profonds",
  },
  1105: {
    "Wildcard/default — matches anything": "Caractère générique/par défaut — correspond à n'importe quelle valeur",
    "Matches the underscore character": "Correspond au caractère de soulignement",
  },
  1108: {
    "No match — lists can't be matched": "Aucune correspondance — les listes ne peuvent pas être appariées",
  },
  1109: {
    "Yes — case int() matches any integer": "Oui — le cas int() correspond à n'importe quel entier",
    "No — type matching is not supported": "Non, la correspondance de types n'est pas prise en charge.",
  },
  1112: {
    "Structural pattern matching": "Appariement de modèles structurels",
  },
  1113: {
    "No match — dicts can't be matched": "Aucune correspondance — les dictionnaires ne peuvent pas être appariés",
  },
  1114: {
    "Yes — extra keys are ignored": "Oui, les touches supplémentaires sont ignorées.",
    "No — all keys must be present": "Non — toutes les clés doivent être présentes",
  },
  1125: {
    "Nothing — execution continues past the match block": "Rien — l'exécution se poursuit au-delà du bloc de correspondance",
  },
  1128: {
    "Yes — __match_args__ defines positional pattern fields": "Oui — __match_args__ définit des champs de modèle positionnel",
    "No — only built-in types work": "Non, seuls les types intégrés fonctionnent.",
    "Yes — __init__ is used automatically": "Oui — __init__ est utilisé automatiquement",
    "Yes — __slots__ defines the fields": "Oui — __slots__ définit les champs",
  },
  1131: {
    "Assigns and returns a value in one expression": "Attribue et renvoie une valeur en une seule expression",
  },
  1141: {
    "No — it raises SyntaxError": "Non, cela génère une erreur de syntaxe.",
    "Yes — but only with default args": "Oui, mais uniquement avec les arguments par défaut.",
  },
  1142: {
    "No — bare x := 5 is a SyntaxError": "Non — x nu := 5 est une erreur de syntaxe",
    "It works but is deprecated": "Cela fonctionne, mais c'est obsolète.",
  },
  1212: {
    "d becomes {'a':1,'b':2,'c':3}": "d devient {'a':1,'b':2,'c':3}",
  },
  1223: {
    "Iteration order is not guaranteed": "L'ordre des itérations n'est pas garanti.",
    "Elements appear in insertion order": "Les éléments apparaissent dans l'ordre d'insertion",
  },
  1241: {
    "Loop that runs once then breaks": "Boucle qui s'exécute une seule fois puis s'interrompt",
  },
  1249: {
    "Yes, but it doesn't affect iteration": "Oui, mais cela n'affecte pas l'itération.",
  },
  1299: {
    "{'name': 'Alice', 'age': 30}": "{'name': 'Alice', 'age': 30}",
    "{'Alice': 'name', 30: 'age'}": "{'Alice': 'nom', 30: 'âge'}",
  },
  1536: {
    "append adds one item, extend adds multiple": "append ajoute un élément, extend en ajoute plusieurs",
  },
  1537: {
    "+ creates new list, extend modifies": "+ crée une nouvelle liste, étend les modifications",
  },
  1546: {
    "pop uses index, remove uses value": "pop utilise l'index, remove utilise la valeur",
  },
  1565: {
    "sort() modifies in place, sorted() returns new list": "sort() modifie la liste sur place, sorted() renvoie une nouvelle liste",
  },
  1566: {
    "list_reverseiterator object": "objet list_reverseiterator",
  },
  1574: {
    "Shallow copies outer, deep copies nested": "Copies superficielles externes, copies profondes imbriquées",
  },
  1627: {
    "Yes, the trailing comma makes it a tuple": "Oui, la virgule finale en fait un tuple.",
    "Yes, the parentheses make it a tuple": "Oui, les parenthèses en font un tuple.",
  },
  1628: {
    "No, it's just the integer 1 with grouping parentheses": "Non, c'est simplement l'entier 1 avec des parenthèses de regroupement.",
    "Yes, it's a tuple with one element": "Oui, c'est un tuple avec un seul élément",
  },
  1642: {
    "Only if the tuple has one element": "Uniquement si le tuple contient un seul élément",
  },
  1645: {
    "Swaps the values of a and b": "Échange les valeurs de a et b",
  },
  1649: {
    "Yes, tuples of immutable elements are hashable": "Oui, les tuples d'éléments immuables sont hachables.",
    "No, tuples are not hashable": "Non, les tuples ne sont pas hachables.",
    "Only if the tuple has one element": "Uniquement si le tuple contient un seul élément",
  },
  1650: {
    "No, TypeError because the list inside is unhashable": "Non, TypeError car la liste interne n'est pas hachable.",
    "Yes, it returns a hash value": "Oui, elle renvoie une valeur de hachage",
    "Yes, tuples are always hashable": "Oui, les tuples sont toujours hachables.",
    "No, only single-element tuples are hashable": "Non, seuls les tuples à un seul élément sont hachables.",
  },
  1738: {
    "All elements are processed": "Tous les éléments sont traités",
    "Python raises RuntimeError": "Python génère une erreur d'exécution",
  },
  1786: {
    "<class 'list_reverseiterator'>": "<class 'list_reverseiterator'>",
  },
  1817: {
    "setdefault() sets key if missing, get() doesn't": "La fonction `setdefault()` définit la clé si elle est manquante, contrairement à `get()`.",
    "setdefault() is deprecated": "La fonction setdefault() est obsolète.",
  },
  1848: {
    "| creates new dict, |= modifies in place": "| crée un nouveau dictionnaire, |= modifie directement",
  },
  2001: {
    "Counter({'l': 2, 'h': 1, 'e': 1, 'o': 1})": "Compteur({'l': 2, 'h': 1, 'e': 1, 'o': 1})",
    "Counter({'h': 1, 'e': 1, 'l': 2, 'o': 1})": "Compteur({'h': 1, 'e': 1, 'l': 2, 'o': 1})",
  },
  2005: {
    "All elements sorted by count descending": "Tous les éléments sont triés par nombre décroissant",
    "Only elements with count > 1": "Seuls les éléments dont le nombre est supérieur à 1",
    "The single most common element": "L'élément le plus courant",
  },
  2008: {
    "Counter({'b': 2, 'c': 2, 'a': 1, 'd': 1})": "Compteur({'b': 2, 'c': 2, 'a': 1, 'd': 1})",
    "Counter({'a': 1, 'b': 1, 'c': 1, 'd': 1})": "Compteur({'a': 1, 'b': 1, 'c': 1, 'd': 1})",
    "Counter({'a': 1, 'b': 2, 'c': 2, 'd': 1})": "Compteur({'a': 1, 'b': 2, 'c': 2, 'd': 1})",
  },
  2009: {
    "Counter({'a': 1, 'b': 0, 'c': 0})": "Compteur({'a': 1, 'b': 0, 'c': 0})",
    "Counter({'a': 1, 'b': -1})": "Compteur({'a': 1, 'b': -1})",
  },
  2010: {
    "Counter({'a': 1, 'b': 1, 'c': 1, 'd': 1})": "Compteur({'a': 1, 'b': 1, 'c': 1, 'd': 1})",
  },
  2011: {
    "Counter({'a': 2, 'c': 2, 'b': 1})": "Compteur({'a': 2, 'c': 2, 'b': 1})",
    "Counter({'a': 2, 'b': 2, 'c': 2})": "Compteur({'a': 2, 'b': 2, 'c': 2})",
    "Counter({'a': 2, 'b': 1, 'c': 2})": "Compteur({'a': 2, 'b': 1, 'c': 2})",
  },
  2017: {
    "Counter({'a': 4, 'b': 2, 'c': 0, 'd': -2})": "Compteur({'a': 4, 'b': 2, 'c': 0, 'd': -2})",
    "Counter({'a': 4, 'b': 2, 'c': 0})": "Compteur({'a': 4, 'b': 2, 'c': 0})",
  },
  2018: {
    "Counter({'a': -4, 'b': -2, 'd': 2})": "Compteur({'a': -4, 'b': -2, 'd': 2})",
  },
  2023: {
    "Counter({'h': 0, 'e': 0, 'l': 0, 'o': 0})": "Compteur({'h': 0, 'e': 0, 'l': 0, 'o': 0})",
  },
  2040: {
    "defaultdict(<class 'int'>, {})": "defaultdict(<class 'int'>, {})",
  },
  2053: {
    "No, tuples of hashable elements are hashable": "Non, les tuples d'éléments hachables sont hachables.",
    "Only if the tuple has < 3 elements": "Uniquement si le tuple contient moins de 3 éléments",
  },
  2054: {
    "TypeError: unhashable type: 'list'": "TypeError : type impossible à hacher : « liste »",
  },
  2055: {
    "No, frozensets are hashable": "Non, les ensembles gelés sont hachables",
  },
  2064: {
    "No, instances are unhashable": "Non, les instances ne sont pas hachables.",
    "Only with __hash__ defined": "Uniquement avec __hash__ défini",
  },
  2067: {
    "TypeError: unhashable type": "TypeError : type non hachable",
  },
  2103: {
    "Defines function returning None": "Définit une fonction renvoyant None",
    "Defines function returning empty": "Définit une fonction renvoyant une valeur vide",
  },
  2104: {
    "Defines function returning tuple": "Définit une fonction renvoyant un tuple",
    "Defines function returning two values": "Définit une fonction renvoyant deux valeurs",
  },
  2106: {
    "Defines function with two parameters": "Définit une fonction à deux paramètres",
  },
  2111: {
    "Defines function with default parameter": "Définit une fonction avec un paramètre par défaut",
    "Defines function with required parameter": "Définit une fonction avec le paramètre requis",
  },
  2113: {
    "Defines function with required and default parameter": "Définit une fonction avec des paramètres obligatoires et par défaut",
    "Defines function with two defaults": "Définit une fonction avec deux valeurs par défaut",
  },
  2116: {
    "Defines function with mutable default (problematic)": "Définit une fonction avec une valeur par défaut modifiable (problématique)",
    "Defines function with immutable default": "Définit une fonction avec une valeur par défaut immuable",
  },
  2117: {
    "Defines function with safe mutable default pattern": "Définit une fonction avec un modèle par défaut mutable et sûr",
    "Defines function with mutable default": "Définit une fonction avec une valeur par défaut modifiable",
  },
  2119: {
    "Defines function with multiple defaults": "Définit une fonction avec plusieurs valeurs par défaut",
    "Defines function with required params": "Définit la fonction avec les paramètres requis",
  },
  2121: {
    "Defines function accepting variable positional arguments": "Définit une fonction acceptant des arguments positionnels variables",
    "Defines function with required args": "Définit une fonction avec les arguments requis",
  },
  2124: {
    "Defines function with required param and *args": "Définit une fonction avec les paramètres requis et *args",
    "Defines function with only *args": "Définit une fonction avec uniquement des arguments *args",
  },
  2126: {
    "Defines function accepting variable keyword arguments": "Définit une fonction acceptant des arguments nommés variables",
    "Defines function with required kwargs": "Définit une fonction avec les arguments nommés requis",
  },
  2129: {
    "Defines function with all parameter types": "Définit une fonction avec tous les types de paramètres",
    "Defines function with only *args": "Définit une fonction avec uniquement des arguments *args",
  },
  2133: {
    "Anonymous function with no parameters": "Fonction anonyme sans paramètres",
  },
  2135: {
    "Anonymous function with two parameters": "Fonction anonyme à deux paramètres",
  },
  2138: {
    "Anonymous function with conditional": "Fonction anonyme avec condition",
  },
  2140: {
    "def creates named function, lambda creates anonymous": "def crée une fonction nommée, lambda crée une fonction anonyme",
  },
  2141: {
    "Defines function returning 1": "Définit une fonction renvoyant 1",
  },
  2143: {
    "Defines function returning tuple (1, 2, 3)": "Définit une fonction renvoyant un tuple (1, 2, 3)",
    "Defines function returning three values": "Définit une fonction renvoyant trois valeurs",
  },
  2146: {
    "Defines function returning None": "Définit une fonction renvoyant None",
    "Defines function with no return": "Définit une fonction sans retour",
  },
  2148: {
    "Defines function returning None": "Définit une fonction renvoyant None",
    "Defines function with no return": "Définit une fonction sans retour",
  },
  2150: {
    "Defines function returning list": "Définit une fonction renvoyant une liste",
    "Defines function returning tuple": "Définit une fonction renvoyant un tuple",
  },
  2166: {
    "RecursionError (infinite recursion)": "Erreur de récursion (récursion infinie)",
  },
  2192: {
    "{'x': <class 'int'>, 'return': <class 'int'>}": "{'x': <class 'int'>, 'return': <class 'int'>}",
  },
  2206: {
    "Allows inner function to modify a variable from the enclosing scope": "Permet à une fonction interne de modifier une variable de la portée englobante",
    "Declares a global variable": "Déclare une variable globale",
    "Creates a new local variable": "Crée une nouvelle variable locale",
  },
  2207: {
    "Yes, it accesses the module-level variable": "Oui, elle accède à la variable de niveau module",
    "No, only nonlocal works in nested functions": "Non, seules les fonctions non locales fonctionnent dans les fonctions imbriquées.",
    "Yes, but it causes an error": "Oui, mais cela provoque une erreur",
    "No, nested functions cannot access any outer variables": "Non, les fonctions imbriquées ne peuvent pas accéder aux variables externes.",
  },
  2216: {
    "A function that remembers variables from its enclosing scope even after that scope has finished": "Une fonction qui conserve en mémoire les variables de sa portée englobante même après la fin de cette portée.",
    "A function that cannot access outside variables": "Une fonction qui ne peut pas accéder aux variables externes",
    "A way to lock a function from being modified": "Un moyen d'empêcher la modification d'une fonction",
    "A function that runs automatically": "Une fonction qui s'exécute automatiquement",
  },
  2236: {
    "Yes, functions are first-class objects": "Oui, les fonctions sont des objets de première classe",
    "Only lambda functions can be stored": "Seules les fonctions lambda peuvent être stockées",
    "Only built-in functions can be stored": "Seules les fonctions intégrées peuvent être enregistrées",
  },
  2238: {
    "Only lambdas can be returned": "Seules les valeurs lambda peuvent être renvoyées.",
    "Only if using return keyword": "Uniquement si le mot-clé return est utilisé",
  },
  2240: {
    "<class 'builtin_function_or_method'>": "<class 'builtin_function_or_method'>",
  },
  2249: {
    "The default object is created once and shared across all calls": "L'objet par défaut est créé une seule fois et partagé entre tous les appels.",
    "It makes the function slower": "Cela ralentit la fonction",
    "It prevents the function from being called": "Cela empêche l'appel de la fonction.",
  },
  2250: {
    "Use None as default and create the object inside the function": "Utilisez None par défaut et créez l'objet à l'intérieur de la fonction",
    "Use a global variable instead": "Utilisez plutôt une variable globale",
    "Use a tuple instead of a list": "Utilisez un tuple au lieu d'une liste",
  },
  2295: {
    "<class 'builtin_function_or_method'>": "<class 'builtin_function_or_method'>",
  },
  2301: {
    "A function that takes a function and returns a modified function": "Une fonction qui prend une fonction et renvoie une fonction modifiée",
    "A class that inherits from another class": "Une classe qui hérite d'une autre classe",
    "A loop that iterates over functions": "Une boucle qui itère sur des fonctions",
    "A variable that stores function names": "Une variable qui stocke les noms des fonctions",
  },
  2302: {
    "my_decorator = func(my_decorator)": "mon_décorateur = fonction(mon_décorateur)",
    "func.decorator = my_decorator": "fonction.décorateur = mon_décorateur",
  },
  2305: {
    "Prints function name before each call": "Affiche le nom de la fonction avant chaque appel",
    "Prints function name after each call": "Affiche le nom de la fonction après chaque appel",
    "Prevents the function from being called": "Empêche l'appel de la fonction",
  },
  2306: {
    "Yes, but adds extra behavior before/after": "Oui, mais cela ajoute un comportement supplémentaire avant/après",
    "No, it replaces the function entirely": "Non, cela remplace complètement la fonction.",
    "Yes, it does nothing at all": "Oui, ça ne fait absolument rien",
    "No, it deletes the function": "Non, cela supprime la fonction",
  },
  2309: {
    "Preserves the decorated function's __name__, __doc__, and other attributes": "Préserve les attributs __name__, __doc__ et autres attributs de la fonction décorée",
    "Makes the decorator run faster": "Cela fait courir le décorateur plus vite.",
    "Prevents the decorator from modifying the function": "Empêche le décorateur de modifier la fonction",
    "Automatically calls the wrapped function": "Appelle automatiquement la fonction encapsulée",
  },
  2310: {
    "Yes: @dec1 then @dec2 means func = dec1(dec2(func))": "Oui : @dec1 puis @dec2 signifie func = dec1(dec2(func))",
    "No, only one decorator per function": "Non, un seul décorateur par fonction",
    "Yes, but only built-in decorators": "Oui, mais seulement les décorateurs intégrés",
    "Yes, but order doesn't matter": "Oui, mais l'ordre n'a pas d'importance.",
  },
  2313: {
    "3 (factory, decorator, wrapper)": "3 (usine, décorateur, emballage)",
    "4 (outer, factory, decorator, wrapper)": "4 (extérieur, usine, décorateur, emballage)",
  },
  2314: {
    "Timing/profiling decorator": "décorateur de timing/profilage",
  },
  2315: {
    "Yes, any callable works (class with __call__)": "Oui, toute fonction appelable fonctionne (classe avec __call__).",
    "No, decorators must be functions": "Non, les décorateurs doivent être des fonctions",
    "Only if the class inherits from Decorator": "Uniquement si la classe hérite de Decorator",
    "Only for built-in decorators": "Uniquement pour les décorateurs intégrés",
  },
  2319: {
    "Yes, decorators can be applied to classes too": "Oui, on peut aussi appliquer des décorateurs aux classes.",
    "No, only functions can be decorated": "Non, seules les fonctions peuvent être décorées.",
    "Only @dataclass can decorate classes": "Seule l'annotation `@dataclass` peut décorer les classes.",
    "Only abstract decorators work on classes": "Seuls les décorateurs abstraits fonctionnent sur les classes",
  },
  2321: {
    "Number of times function is called": "La fonction est appelée le nombre de fois.",
    "Arguments passed to function": "Arguments passés à la fonction",
  },
  2324: {
    "Turns a method into a read-only attribute": "Transforme une méthode en un attribut en lecture seule",
    "Makes an attribute private": "Rend un attribut privé",
  },
  2328: {
    "classmethod receives the class as first arg, staticmethod doesn't": "La méthode de classe reçoit la classe comme premier argument, contrairement à la méthode statique.",
    "staticmethod is faster than classmethod": "La méthode statique est plus rapide que la méthode de classe.",
    "classmethod can only be called on instances": "La méthode de classe ne peut être appelée que sur des instances",
    "staticmethod automatically creates instances": "staticmethod crée automatiquement des instances",
  },
  2331: {
    "Nothing — returns function unchanged (identity decorator)": "Rien — renvoie la fonction inchangée (décorateur d'identité)",
    "Wraps the function in a class": "Encapsule la fonction dans une classe",
    "Doubles the function's output": "Double le résultat de la fonction",
  },
  2332: {
    "Yes, but calling the decorated name will fail since 42 is not callable": "Oui, mais l'appel du nom décoré échouera car 42 n'est pas appelable.",
    "No, decorators must return functions": "Non, les décorateurs doivent renvoyer des fonctions",
    "Yes, and calling it will return 42": "Oui, et l'appel renverra 42",
  },
  2333: {
    "TypeError: 'int' object is not callable": "TypeError : l’objet « int » n’est pas appelable",
  },
  2334: {
    "Authorization/permission decorator": "décorateur d'autorisation/de permission",
  },
  2335: {
    "Not easily; you'd need __wrapped__ if functools.wraps was used": "Pas facilement ; il faudrait utiliser __wrapped__ si functools.wraps était utilisé.",
    "Yes, just call undecorate(f)": "Oui, il suffit d'appeler undecorate(f)",
    "Decorators are always removable": "Les décorateurs sont toujours amovibles",
  },
  2337: {
    "No, @ syntax requires def, but you can manually: f = decorator(lambda: ...)": "Non, la syntaxe @ requiert def, mais vous pouvez le faire manuellement : f = decorator(lambda: ...)",
    "Yes, use @decorator before lambda": "Oui, utilisez @decorator avant lambda",
    "Yes, lambda supports all decorators": "Oui, lambda prend en charge tous les décorateurs",
    "No, lambdas cannot be decorated at all": "Non, les lambdas ne peuvent pas être décorées du tout",
  },
  2339: {
    "At decoration time (when @dec is applied), not when f() is called": "Au moment de la décoration (lorsque @dec est appliqué), et non lorsque f() est appelé",
    "When the module is imported AND when f() is called": "Lorsque le module est importé ET lorsque f() est appelé",
    "Never — print is inside dec but dec is never called": "Jamais — l'impression est à l'intérieur de déc mais déc n'est jamais appelé",
  },
  2340: {
    "Yes, the wrapper can transform args before passing to original": "Oui, le wrapper peut transformer les arguments avant de les transmettre à l'original.",
    "No, arguments are always passed unchanged": "Non, les arguments sont toujours transmis sans modification.",
    "Only keyword arguments can be modified": "Seuls les arguments nommés peuvent être modifiés.",
    "Only if the function has *args": "Uniquement si la fonction a des *args",
  },
  2345: {
    "Traces function entry and exit with return value": "Trace l'entrée et la sortie de la fonction avec la valeur de retour",
    "Only traces function entry": "Seules les traces de l'entrée de fonction",
    "Only traces the return value": "Ne trace que la valeur de retour",
    "Prevents the function from running": "Empêche l'exécution de la fonction",
  },
  2346: {
    "A decorator that marks methods as abstract (must be overridden)": "Un décorateur qui marque les méthodes comme abstraites (doit être redéfini)",
    "A function that creates abstract classes": "Une fonction qui crée des classes abstraites",
    "A method that deletes class attributes": "Une méthode qui supprime les attributs de classe",
    "A decorator that makes methods private": "Un décorateur qui rend les méthodes privées",
  },
  2347: {
    "Auto-generates comparison methods from __eq__ and one of __lt__, __gt__, etc.": "Génère automatiquement des méthodes de comparaison à partir de __eq__ et de l'une des méthodes suivantes : __lt__, __gt__, etc.",
    "Sorts all instances automatically": "Trie automatiquement toutes les instances",
    "Adds __hash__ to the class": "Ajoute __hash__ à la classe",
  },
  2348: {
    "Via closure — the original function is captured in the wrapper's enclosing scope": "Par le biais d'une fermeture, la fonction d'origine est capturée dans la portée englobante du wrapper.",
  },
  2349: {
    "A context manager (for use with 'with' statement)": "Un gestionnaire de contexte (à utiliser avec l'instruction 'with')",
  },
  2367: {
    "Creates a new function with some arguments pre-filled": "Crée une nouvelle fonction avec certains arguments pré-remplis.",
    "Executes a function partially": "Exécute partiellement une fonction",
    "Splits a function into parts": "Décompose une fonction en parties",
    "Removes arguments from a function": "Supprime les arguments d'une fonction",
  },
  2370: {
    "The original function (pow)": "La fonction originale (pow)",
    "The partial function itself": "La fonction partielle elle-même",
  },
  2372: {
    "It caches previously computed results": "Il met en cache les résultats précédemment calculés",
    "It parallelizes the computation": "Il parallélise le calcul",
  },
  2373: {
    "Maximum number of cached results": "Nombre maximal de résultats mis en cache",
  },
  2374: {
    "hits=1, misses=1, maxsize=128, currsize=1": "succès=1, échecs=1, taille maximale=128, taille actuelle=1",
    "hits=2, misses=0, maxsize=128, currsize=1": "succès=2, échecs=0, taille maximale=128, taille actuelle=1",
    "hits=0, misses=2, maxsize=128, currsize=2": "succès=0, échecs=2, taille maximale=128, taille actuelle=2",
  },
  2376: {
    "No, arguments must be hashable": "Non, les arguments doivent être hachables.",
    "Yes, it works with any type": "Oui, cela fonctionne avec n'importe quel type",
    "Yes, but only with maxsize=None": "Oui, mais seulement avec maxsize=None",
  },
  2377: {
    "Unlimited cache size (caches everything)": "Taille du cache illimitée (tout est mis en cache)",
  },
  2378: {
    "Same as lru_cache(maxsize=None)": "Identique à lru_cache(maxsize=None)",
    "A different caching mechanism": "Un mécanisme de mise en cache différent",
    "A cache decorator with maxsize=1": "Un décorateur de cache avec maxsize=1",
  },
  2379: {
    "Yes, different argument tuples are cached separately": "Oui, les différents tuples d'arguments sont mis en cache séparément.",
    "No, they return the same result so one entry": "Non, ils renvoient le même résultat, donc une seule entrée",
  },
  2380: {
    "Yes, but self is part of the cache key": "Oui, mais « self » fait partie de la clé de cache.",
    "No, it only works on module-level functions": "Non, cela ne fonctionne que sur les fonctions au niveau du module.",
  },
  2381: {
    "Generic function dispatch based on the type of the first argument": "Dispatch de fonction générique basé sur le type du premier argument",
    "A way to call functions asynchronously": "Une méthode pour appeler des fonctions de manière asynchrone",
    "A method to dispatch events": "Une méthode pour déclencher des événements",
    "A decorator for class methods only": "Un décorateur uniquement pour les méthodes de classe",
  },
  2389: {
    "Gets object attributes by name": "Récupère les attributs d'un objet par leur nom",
    "Gets dictionary items by key": "Récupère les éléments du dictionnaire par clé",
    "Gets list elements by index": "Récupère les éléments de la liste par index",
  },
  2396: {
    "A dictionary of local variables": "Un dictionnaire de variables locales",
  },
  2397: {
    "A dictionary of global variables": "Un dictionnaire de variables globales",
    "A list of all defined functions": "Liste de toutes les fonctions définies",
  },
  2402: {
    "Defines class with class attribute": "Définit une classe avec un attribut de classe",
  },
  2404: {
    "Creates instance of MyClass": "Crée une instance de MyClass",
  },
  2405: {
    "<class '__main__.MyClass'>": "<class '__main__.MyClass'>",
  },
  2414: {
    "Creates instance with x=1, y=2": "Crée une instance avec x=1, y=2",
  },
  2429: {
    "<bound method MyClass.method>": "<bound method MyClass.method>",
  },
  2441: {
    "<class '__main__.MyClass'>": "<class '__main__.MyClass'>",
  },
  2442: {
    "<class '__main__.MyClass'>": "<class '__main__.MyClass'>",
  },
  2445: {
    "classmethod gets cls, staticmethod gets nothing": "La méthode de classe reçoit cls, la méthode statique ne reçoit rien",
  },
  2480: {
    "Dict with class attributes": "Dictionnaire avec attributs de classe",
  },
  2492: {
    "AttributeError (no __dict__)": "Erreur d'attribut (aucun __dict__)",
  },
  2494: {
    "Dict with class attributes and methods": "Dictionnaire contenant les attributs et méthodes de classe",
  },
  2496: {
    "<class '__main__.MyClass'>": "<class '__main__.MyClass'>",
  },
  2497: {
    "<class '__main__.MyClass'>": "<class '__main__.MyClass'>",
  },
  2500: {
    "Method Resolution Order list": "Liste de résolution des méthodes",
  },
  2505: {
    "Comparison with > operator": "Comparaison avec l'opérateur >",
  },
  2514: {
    "Reflected add when left operand doesn't support +": "Addition réfléchie lorsque l'opérande de gauche ne prend pas en charge le +",
  },
  2528: {
    "The iterator object itself (self)": "L'objet itérateur lui-même (self)",
  },
  2540: {
    "Iterable has __iter__; iterator has both __iter__ and __next__": "Iterable possède __iter__; iterator possède à la fois __iter__ et __next__",
    "Iterable has __next__; iterator has __iter__": "Itérable possède __next__; itérateur possède __iter__",
    "Iterable is a class; iterator is a function": "Iterable est une classe ; iterator est une fonction",
  },
  2543: {
    "The value bound to the 'as' variable": "La valeur liée à la variable 'as'",
  },
  2544: {
    "Exception type, value, and traceback": "Type d'exception, valeur et trace d'exécution",
    "The return value of __enter__": "La valeur de retour de __enter__",
  },
  2546: {
    "Yes, with a generator function": "Oui, avec une fonction génératrice",
  },
  2547: {
    "A file object that is also a context manager": "Un objet fichier qui est également un gestionnaire de contexte",
  },
  2548: {
    "__exit__ is called with the exception info": "__exit__ est appelé avec les informations d'exception",
    "The program crashes immediately": "Le programme plante immédiatement",
  },
  2549: {
    "Yes, both nesting and multiple items are supported": "Oui, l'imbrication et la gestion de plusieurs éléments sont prises en charge.",
    "Only nesting, not multiple items": "Uniquement des éléments imbriqués, pas plusieurs éléments",
  },
  2550: {
    "Ensure cleanup even if exceptions occur": "Assurez-vous d'effectuer le nettoyage même en cas d'exceptions.",
  },
  2608: {
    "TypeError — non-default field after default field": "TypeError — champ non par défaut après un champ par défaut",
  },
  2610: {
    "Mutable default would be shared across all instances": "La valeur par défaut modifiable serait partagée entre toutes les instances",
    "Lists cannot be type-annotated": "Les listes ne peuvent pas être annotées avec un type.",
  },
  2612: {
    "Makes instances immutable — attributes cannot be changed": "Rend les instances immuables — les attributs ne peuvent pas être modifiés",
    "Freezes the class so no subclasses can be created": "Gele la classe afin qu'aucune sous-classe ne puisse être créée.",
    "Prevents the class from being imported": "Empêche l'importation de la classe",
  },
  2613: {
    "Yes — frozen dataclasses are hashable": "Oui, les classes de données figées sont hachables.",
    "No — dataclasses are never hashable": "Non — les classes de données ne sont jamais hachables",
    "Only if __hash__ is manually defined": "Uniquement si __hash__ est défini manuellement",
  },
  2620: {
    "Yes, just like regular classes": "Oui, tout comme les cours réguliers",
    "Only if you disable __repr__": "Uniquement si vous désactivez __repr__",
  },
  2622: {
    "Called after __init__ for custom initialization logic": "Appelée après __init__ pour une logique d'initialisation personnalisée",
    "Replaces __init__ entirely": "Remplace entièrement __init__",
    "Only used for type checking": "Utilisé uniquement pour la vérification des types",
  },
  2624: {
    "Disables the auto-generated __repr__ method": "Désactive la méthode __repr__ générée automatiquement",
    "Makes the class invisible to print()": "Rend la classe invisible à print()",
    "Prevents instance creation": "Empêche la création d'instances",
  },
  2637: {
    "AttributeError — can't modify enum values": "Erreur d'attribut : impossible de modifier les valeurs de l'énumération",
  },
  2644: {
    "A new namedtuple with updated values (original unchanged)": "Un nouveau namedtuple avec des valeurs mises à jour (les valeurs originales restent inchangées)",
    "The same namedtuple, modified in place": "Le même tuple nommé, modifié sur place",
    "None — it modifies in place": "Aucun — il modifie sur place",
    "A dictionary of changed fields": "Un dictionnaire des champs modifiés",
  },
  2649: {
    "Namedtuples are immutable and are tuple subclasses": "Les tuples nommés sont immuables et sont des sous-classes de tuples.",
    "Dataclasses are immutable by default": "Les classes de données sont immuables par défaut",
    "Namedtuples support methods but dataclasses don't": "Les Namedtuples prennent en charge les méthodes, mais pas les dataclasses.",
    "Namedtuples cannot have default values": "Les tuples nommés ne peuvent pas avoir de valeurs par défaut",
  },
  2651: {
    "An object defining __get__, __set__, or __delete__": "Un objet définissant __get__, __set__ ou __delete__",
  },
  2652: {
    "__get__, __set__, __delete__": "__get__, __set__, __delete__",
  },
  2653: {
    "Both __get__ and __set__ (or __delete__)": "Les deux __get__ et __set__ (ou __delete__)",
  },
  2656: {
    "Lower than instance __dict__": "Inférieur à l'instance __dict__",
    "Higher than instance __dict__": "Supérieur à l'instance __dict__",
    "Equal to instance __dict__": "Égal à l'instance __dict__",
    "Higher than data descriptors": "Supérieur aux descripteurs de données",
  },
  2662: {
    "Called when descriptor is assigned to a class attribute": "Appelée lorsque le descripteur est affecté à un attribut de classe",
  },
  2664: {
    "Bind self to create bound methods": "Liez-vous pour créer des méthodes liées",
  },
  2668: {
    "Implement the decorated method": "Implémentez la méthode décorée",
  },
  2671: {
    "Yes: combine @property and @abstractmethod": "Oui : combinez @property et @abstractmethod",
    "No, properties can't be abstract": "Non, les propriétés ne peuvent pas être abstraites.",
  },
  2675: {
    "Automatic Base Constructor": "Constructeur de base automatique",
  },
  2680: {
    "A class to be considered a subclass without inheritance": "Une classe considérée comme une sous-classe sans héritage",
  },
  2681: {
    "A class whose instances are classes": "Une classe dont les instances sont des classes",
    "A class that can't be instantiated": "Une classe qui ne peut pas être instanciée",
  },
  2693: {
    "A dict with str keys and int values": "Un dictionnaire avec des clés de type chaîne de caractères et des valeurs de type entier.",
    "A dict with int keys and str values": "Un dictionnaire avec des clés de type int et des valeurs de type str",
  },
  2694: {
    "A tuple of exactly (int, str)": "Un tuple de exactement (int, str)",
  },
  2698: {
    "Structural subtyping (duck typing with type checking)": "Sous-typage structurel (typage canard avec vérification de type)",
    "A network protocol handler": "Un gestionnaire de protocole réseau",
  },
  2701: {
    "Child class gets parent features": "La classe enfant hérite des fonctionnalités de la classe parente",
    "Parent class gets child features": "La classe parente obtient des fonctionnalités enfant",
  },
  2706: {
    "(<class '__main__.Parent'>,)": "(<class '__main__.Parent'>,)",
  },
  2711: {
    "Child redefines parent method": "L'enfant redéfinit la méthode du parent",
    "Parent redefines child method": "Le parent redéfinit la méthode enfant",
    "Methods cannot be redefined": "Les méthodes ne peuvent pas être redéfinies",
  },
  2735: {
    "(<class '__main__.A'>, <class '__main__.B'>)": "(<class '__main__.A'>, <class '__main__.B'>)",
  },
  2741: {
    "Same interface, different behavior": "Même interface, comportement différent",
    "Same behavior, different interface": "Même comportement, interface différente",
  },
  2780: {
    "TypeError (can't instantiate)": "TypeError (impossible d'instancier)",
  },
  2798: {
    "<class '__main__.MyClass'>": "<class '__main__.MyClass'>",
  },
  2859: {
    "Immutable objects are set up in __new__ before __init__ runs": "Les objets immuables sont initialisés dans __new__ avant l'exécution de __init__.",
    "__init__ doesn't exist for immutable types": "__init__ n'existe pas pour les types immuables",
    "__new__ is faster than __init__": "__new__ est plus rapide que __init__",
    "__init__ only works for mutable types": "__init__ ne fonctionne que pour les types mutables",
  },
  2868: {
    "List of direct subclasses of A": "Liste des sous-classes directes de A",
    "List of all instances of A": "Liste de toutes les occurrences de A",
    "List of parent classes of A": "Liste des classes parentes de A",
  },
  2871: {
    "When a class is subclassed (at class definition time)": "Lorsqu'une classe est sous-classée (au moment de la définition de la classe)",
    "When an instance is created": "Lorsqu'une instance est créée",
    "When the class is garbage collected": "Lorsque la classe est collectée par le ramasse-miettes",
  },
  2878: {
    "Raises NotImplementedError": "Lève une erreur NotImplementedError",
  },
  2879: {
    "abstractmethod prevents instantiation; NotImplementedError allows it": "AbstractMethod empêche l'instanciation ; NotImplementedError l'autorise.",
    "NotImplementedError prevents instantiation": "L'erreur NotImplementedError empêche l'instanciation",
    "abstractmethod only works with functions, not methods": "abstractmethod ne fonctionne qu'avec les fonctions, pas avec les méthodes.",
  },
  2905: {
    "Yes, subclasses can call it with super()": "Oui, les sous-classes peuvent l'appeler avec super()",
    "No, ABCs cannot have __init__": "Non, les ABC ne peuvent pas avoir d'initialisation.",
    "Only if __init__ is abstract": "Uniquement si __init__ est abstrait",
  },
  2908: {
    "Yes, subclasses can call it via super()": "Oui, les sous-classes peuvent l'appeler via super()",
    "No, body is always ignored": "Non, le corps est toujours ignoré.",
  },
  2911: {
    "@classmethod then @abstractmethod": "@classmethod puis @abstractmethod",
    "@abstractmethod then @classmethod": "@abstractmethod puis @classmethod",
    "@staticmethod then @abstractmethod": "@staticmethod puis @abstractmethod",
  },
  2912: {
    "@staticmethod then @abstractmethod": "@staticmethod puis @abstractmethod",
    "@abstractmethod then @staticmethod": "@abstractmethod puis @staticmethod",
  },
  2913: {
    "Only if parent has no abstract methods": "Uniquement si le parent ne possède aucune méthode abstraite",
  },
  2915: {
    "Equivalent to class Shape(ABC)": "Équivalent à la classe Shape(ABC)",
  },
  2919: {
    "Makes list a virtual subclass of MyABC": "Fait de la liste une sous-classe virtuelle de MyABC",
    "Adds MyABC methods to list": "Ajoute les méthodes MyABC à la liste",
    "Makes MyABC inherit from list": "Permet à MyABC d'hériter de la liste",
  },
  2921: {
    "They don't inherit methods": "Ils n'héritent pas des méthodes",
    "They don't pass isinstance checks": "Ils ne réussissent pas les tests isinstance.",
    "They don't pass issubclass checks": "Ils ne passent pas les vérifications issubclass.",
    "They don't allow registration": "Ils n'autorisent pas l'inscription",
  },
  2926: {
    "Defines structural interfaces (duck typing with type checking)": "Définit les interfaces structurelles (typage canard avec vérification de type)",
    "Defines nominal interfaces": "Définit les interfaces nominales",
  },
  2929: {
    "Yes, structurally (has draw method)": "Oui, structurellement (méthode de dessin)",
    "No, doesn't inherit Drawable": "Non, n'hérite pas de Drawable",
  },
  2933: {
    "Use isinstance() checks at runtime": "Utilisez les vérifications isinstance() lors de l'exécution.",
    "Use Protocol without typing": "Utiliser le protocole sans saisir de texte",
  },
  2935: {
    "Any class with __lt__ is Comparable": "Toute classe avec __lt__ est comparable",
    "All classes are Comparable": "Toutes les classes sont comparables",
  },
  2936: {
    "If it walks like a duck and quacks like a duck, it's a duck": "Si ça marche comme un canard et que ça cancane comme un canard, c'est un canard.",
    "All objects must inherit from Duck": "Tous les objets doivent hériter de Duck",
    "Types must be declared explicitly": "Les types doivent être déclarés explicitement.",
  },
  2937: {
    "Duck typing for static type checkers": "Typage dynamique pour les vérificateurs de types statiques",
  },
  2938: {
    "Files, connections, sockets — anything with close()": "Fichiers, connexions, sockets — tout ce qui possède la méthode close()",
    "Nothing matches without inheritance": "Rien ne s'accorde sans héritage",
  },
  2939: {
    "Yes, but classes must explicitly inherit to use them": "Oui, mais les classes doivent explicitement hériter pour les utiliser",
    "Yes, all classes get them automatically": "Oui, toutes les classes les reçoivent automatiquement.",
    "Only with @runtime_checkable": "Uniquement avec @runtime_checkable",
  },
  2942: {
    "Mixin methods: __contains__, __iter__, __reversed__, index, count": "Méthodes Mixin : __contains__, __iter__, __reversed__, index, count",
    "Only __getitem__ and __len__": "Seuls __getitem__ et __len__",
  },
  2943: {
    "__setitem__, __delitem__, insert; plus append, clear, reverse, extend, pop": "__setitem__, __delitem__, insert; plus append, clear, reverse, extend, pop",
  },
  2949: {
    "Yes, just implement all required methods": "Oui, il suffit d'implémenter toutes les méthodes requises.",
    "No, only one Protocol at a time": "Non, un seul protocole à la fois.",
    "Only with multiple inheritance": "Uniquement avec héritage multiple",
    "Only with @runtime_checkable": "Uniquement avec @runtime_checkable",
  },
  2950: {
    "All objects (object has __str__)": "Tous les objets (l'objet possède __str__)",
    "Only objects with custom __str__": "Seuls les objets avec une chaîne de caractères personnalisée __str__",
  },
  2963: {
    "Private by convention (still accessible)": "Privé par convention (toujours accessible)",
    "Truly private (not accessible)": "Vraiment privé (non accessible)",
  },
  2965: {
    "No, dunders are never mangled": "Non, les dunders ne sont jamais mutilés",
  },
  2971: {
    "An algorithm skeleton with overridable steps": "Un squelette d'algorithme avec des étapes modifiables",
    "A list of required attributes": "Liste des attributs requis",
  },
  2973: {
    "Composition over inheritance": "La composition plutôt que l'héritage",
    "Deep inheritance hierarchies": "hiérarchies d'héritage profondes",
  },
  2975: {
    "A method that creates and returns objects": "Une méthode qui crée et renvoie des objets",
  },
  2977: {
    "A list of dependents notified of state changes": "Liste des personnes à charge informées des changements d'état",
    "A fixed algorithm skeleton": "Un squelette d'algorithme fixe",
    "A pool of reusable objects": "Un ensemble d'objets réutilisables",
  },
  2979: {
    "Subclasses should be substitutable for base classes": "Les sous-classes doivent pouvoir remplacer les classes de base.",
    "Classes should have one responsibility": "Les classes devraient avoir une seule responsabilité",
    "Depend on abstractions, not concretions": "S'appuyer sur des abstractions, et non sur des concrétions.",
    "Prefer composition over inheritance": "Privilégier la composition à l'héritage",
  },
  2980: {
    "Yes, if w and h can be set independently": "Oui, si w et h peuvent être réglés indépendamment",
    "Only if area() is overridden": "Uniquement si la fonction area() est redéfinie",
  },
  2981: {
    "Open for extension, closed for modification": "Ouvert à la prolongation, fermé à la modification",
    "Open for modification, closed for extension": "Ouvert aux modifications, fermé à l'extension",
    "Open for deletion, closed for creation": "Ouvert à la suppression, fermé à la création",
    "Open for reading, closed for writing": "Ouvert à la lecture, fermé à l'écriture",
  },
  2983: {
    "Many small, specific interfaces": "De nombreuses petites interfaces spécifiques",
    "One large comprehensive interface": "Une interface unique et complète",
  },
  2984: {
    "Abstractions, not concrete implementations": "Des abstractions, et non des implémentations concrètes",
  },
  2987: {
    "Prints 'Creating Foo' and returns Foo instance": "Affiche « Création de Foo » et renvoie une instance de Foo",
  },
  2988: {
    "When combining behaviors from unrelated sources": "Lors de la combinaison de comportements provenant de sources non liées",
    "When classes share a direct is-a relationship": "Lorsque des classes partagent une relation directe « est-un »",
    "When you need exactly one class": "Lorsque vous avez besoin d'une seule classe",
    "When using only built-in types": "Lorsque vous utilisez uniquement des types intégrés",
  },
  2989: {
    "Add reusable methods without deep hierarchies": "Ajouter des méthodes réutilisables sans hiérarchies profondes",
  },
  2990: {
    "Always uses the first parent": "Utilise toujours le premier parent",
  },
  2991: {
    "ValueError, TypeError, KeyError, etc.": "ValueError, TypeError, KeyError, etc.",
  },
  2992: {
    "No, must inherit BaseException": "Non, il faut hériter de BaseException",
  },
  3000: {
    "So except Exception doesn't accidentally catch them": "Sauf si Exception les intercepte accidentellement",
    "Because they are not errors": "Parce que ce ne sont pas des erreurs",
    "Because Python 2 required it": "Parce que Python 2 l'exigeait",
  },
  3004: {
    "<class 'ZeroDivisionError'>": "<class 'ZeroDivisionError'>",
  },
  3005: {
    "Catches multiple exception types": "Intercepte plusieurs types d'exceptions",
  },
  3011: {
    "Raises ValueError exception": "Lève une exception ValueError",
  },
  3012: {
    "Raises ValueError without message": "Lève une exception ValueError sans message d'erreur.",
  },
  3019: {
    "Catches ValueError (subclass)": "Intercepte ValueError (sous-classe)",
  },
  3036: {
    "Checks if script is run directly": "Vérifie si le script est exécuté directement",
  },
  3037: {
    "Runs code only when script executed": "Exécute le code uniquement lorsque le script est exécuté.",
  },
  3038: {
    "List of module search paths": "Liste des chemins de recherche des modules",
  },
  3040: {
    "Path to current module file": "Chemin d'accès au fichier du module actuel",
  },
  3045: {
    "StopIteration with value 'done'": "Arrêter l'itération avec la valeur 'terminé'",
  },
  3074: {
    "<class '__main__.MyClass'>": "<class '__main__.MyClass'>",
  },
  3085: {
    "Forward reference (string)": "Référence anticipée (chaîne de caractères)",
  },
  3092: {
    "Environment variables dict": "dictionnaire des variables d'environnement",
  },
  3167: {
    "Pretty-prints with 2-space indentation": "Impression soignée avec un retrait de 2 espaces",
    "Adds 2 spaces before the key": "Ajoute 2 espaces avant la touche",
    "Indents only nested objects": "Indenter uniquement les objets imbriqués",
  },
  3175: {
    "TypeError — sets are not JSON serializable": "TypeError — les ensembles ne sont pas sérialisables en JSON",
  },
  3190: {
    "abcdefghijklmnopqrstuvwxyz": "abcdefghijklmnopqrstuvwxyz",
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ": "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
  },
  3191: {
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ": "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    "abcdefghijklmnopqrstuvwxyz": "abcdefghijklmnopqrstuvwxyz",
  },
  3193: {
    "Yes, it contains all ASCII punctuation": "Oui, il contient toute la ponctuation ASCII.",
  },
  3196: {
    "Space, tab, newline, and other whitespace": "Espace, tabulation, saut de ligne et autres espaces blancs",
  },
  3197: {
    "Wraps text into lines of at most 10 characters each": "Regroupe le texte en lignes de 10 caractères maximum.",
    "Truncates to 10 characters": "Tronque à 10 caractères",
  },
  3208: {
    "Sets the root logger to show DEBUG and above": "Configure le journal système racine pour afficher les niveaux DEBUG et supérieurs.",
  },
  3209: {
    "Sends log records to a destination": "Envoie les enregistrements de journal vers une destination",
  },
  3210: {
    "Specifies the layout of log records": "Spécifie la mise en page des enregistrements de journal.",
    "Filters log records by level": "Filtre les enregistrements de journal par niveau",
  },
  3211: {
    "Creates a logger named after the module for hierarchical logging": "Crée un enregistreur de journalisation portant le nom du module pour la journalisation hiérarchique.",
  },
  3213: {
    "Includes traceback information": "Comprend des informations de traçabilité",
  },
  3214: {
    "Logging supports levels, formatting, handlers, and can be configured without code changes": "La journalisation prend en charge les niveaux, le formatage et les gestionnaires, et peut être configurée sans modification du code.",
    "logging only works in modules": "La journalisation ne fonctionne que dans les modules",
  },
  3215: {
    "A handler that writes log records to a file": "Un gestionnaire qui écrit les enregistrements de journal dans un fichier",
    "A new log file with default content": "Un nouveau fichier journal avec contenu par défaut",
    "A formatter for file output": "Un formateur pour la sortie de fichiers",
  },
  3216: {
    "That the values are the same object": "Que les valeurs sont le même objet",
    "That the first value is True": "Que la première valeur soit vraie",
    "That no exception is raised": "Qu'aucune exception ne soit soulevée",
  },
  3219: {
    "That a is b (same object identity)": "Que a est b (même identité d'objet)",
  },
  3222: {
    "That a ValueError is raised": "Une erreur ValueError est levée.",
    "That ValueError is a class": "Cette ValueError est une classe",
  },
  3225: {
    "Runs before each test method": "S'exécute avant chaque méthode de test",
    "Runs once before all tests": "S'exécute une fois avant tous les tests",
    "Initializes the test runner": "Initialise le lanceur de tests",
  },
  3226: {
    "Runs after each test method": "S'exécute après chaque méthode de test",
  },
  3227: {
    "Runs once before all tests in the class": "S'exécute une fois avant tous les tests de la classe",
  },
  3228: {
    "Fails the test with 'reason'": "Échoue au test avec la « raison »",
    "Runs the test but ignores failures": "Exécute le test mais ignore les échecs.",
  },
  3229: {
    "Marks a test that is expected to fail": "Indique un test qui devrait échouer.",
    "Reruns the test on failure": "Relance le test en cas d'échec",
  },
  3233: {
    "Yes, with import assert_off": "Oui, avec import assert_off",
  },
  3234: {
    "Normal mode (False with -O flag)": "Mode normal (Faux avec l'option -O)",
  },
  3235: {
    "A testing framework that extracts tests from docstrings": "Un framework de test qui extrait les tests des docstrings",
    "A tool for documenting tests": "Un outil pour documenter les tests",
  },
  3239: {
    "Always, whether an exception occurred or not": "Toujours, qu'une exception se soit produite ou non",
    "Only when an exception occurs": "Seulement lorsqu'une exception se produit",
    "Only when no exception occurs": "Uniquement lorsqu'aucune exception ne se produit",
    "Only when except is present": "Uniquement lorsque except est présent",
  },
  3240: {
    "Yes, all three can coexist": "Oui, les trois peuvent coexister.",
    "No, else and finally conflict": "Non, sinon et finalement conflit",
    "Only with specific exceptions": "Sauf exceptions particulières",
  },
  3243: {
    "Formatted traceback string of the current exception": "Chaîne de trace d'exécution formatée de l'exception actuelle",
  },
  3244: {
    "A (type, value, traceback) tuple": "Un tuple (type, valeur, traceback)",
    "The exception message string": "La chaîne de message d'exception",
  },
  3246: {
    "All exceptions including SystemExit and KeyboardInterrupt": "Toutes les exceptions, y compris SystemExit et KeyboardInterrupt, sont prises en compte.",
    "Only TypeError and ValueError": "Seules les erreurs de type et de valeur",
  },
  3247: {
    "All exceptions except SystemExit, KeyboardInterrupt, GeneratorExit": "Toutes les exceptions sauf SystemExit, KeyboardInterrupt, GeneratorExit",
    "Exactly the same as bare except": "Exactement la même chose que nu, sauf",
    "Only TypeError and ValueError": "Seules les erreurs de type et de valeur",
  },
  3248: {
    "Easier to Ask Forgiveness than Permission": "Il est plus facile de demander pardon que la permission.",
    "Error And Failure Prevention": "Prévention des erreurs et des défaillances",
    "Exception Aware Function Protocol": "Protocole de fonction sensible aux exceptions",
    "Explicit Action For Processing": "Action explicite pour le traitement",
  },
  3262: {
    "stdlib, third-party, local": "bibliothèque standard, tierce partie, locale",
    "local, third-party, stdlib": "local, tiers, bibliothèque standard",
  },
  3265: {
    "A string literal as the first statement in a module/class/function": "Une chaîne littérale de caractères comme première instruction d'un module/classe/fonction",
    "A variable holding documentation": "Documentation de détention variable",
    "A .txt file describing code": "Un fichier .txt décrivant le code",
  },
  3269: {
    "Just call it like a function": "Appelez-la simplement comme une fonction",
  },
  3270: {
    "Runs the coroutine in an event loop and returns its result": "Exécute la coroutine dans une boucle d'événements et renvoie son résultat",
    "Converts coroutine to a generator": "Convertit une coroutine en générateur",
  },
  3271: {
    "Only inside an async function": "Uniquement à l'intérieur d'une fonction asynchrone",
  },
  3273: {
    "A coroutine that pauses for 1 second without blocking": "Une coroutine qui fait une pause d'une seconde sans blocage",
    "A function that blocks the thread for 1 second": "Une fonction qui bloque le thread pendant 1 seconde",
    "A timer that runs in a separate thread": "Un minuteur qui s'exécute dans un thread séparé",
    "A system call to the OS sleep": "Un appel système à la fonction sleep du système d'exploitation",
  },
  3274: {
    "time.sleep blocks the entire thread": "time.sleep bloque l'intégralité du thread",
    "asyncio.sleep blocks the thread": "asyncio.sleep bloque le thread",
    "time.sleep is non-blocking": "time.sleep n'est pas bloquant",
  },
  3275: {
    "Runs multiple coroutines concurrently and returns all results": "Exécute plusieurs coroutines simultanément et renvoie tous les résultats",
    "Runs coroutines sequentially": "Exécute les coroutines séquentiellement",
    "Creates threads for each coroutine": "Crée des threads pour chaque coroutine",
    "Picks the fastest coroutine result": "Sélectionne le résultat de coroutine le plus rapide",
  },
  3276: {
    "Iterating over asynchronous iterators": "Itération sur des itérateurs asynchrones",
    "Looping faster than regular for": "Boucle plus rapide que la boucle normale pour",
    "Iterating in a separate thread": "Itération dans un thread séparé",
  },
  3277: {
    "Using asynchronous context managers": "Utilisation de gestionnaires de contexte asynchrones",
  },
  3278: {
    "The core that manages and schedules coroutines": "Le noyau qui gère et planifie les coroutines",
    "A for loop that handles events": "Une boucle for qui gère les événements",
  },
  3279: {
    "Schedules the coroutine to run concurrently as a Task": "Planifie l'exécution de la coroutine en parallèle en tant que tâche",
    "Runs the coroutine immediately to completion": "Exécute la coroutine immédiatement jusqu'à son terme.",
    "Converts coroutine to a generator": "Convertit une coroutine en générateur",
  },
  3280: {
    "Yes, but sync calls inside async can block the event loop": "Oui, mais les appels synchrones à l'intérieur d'appels asynchrones peuvent bloquer la boucle d'événements",
    "No, they are completely incompatible": "Non, ils sont totalement incompatibles.",
  },
  3281: {
    "Efficient I/O-bound concurrency without threads": "Concurrence efficace limitée par les E/S sans threads",
    "Automatic parallelism on multiple cores": "Parallélisme automatique sur plusieurs cœurs",
  },
  3289: {
    "for i, x in enumerate(lst):": "pour i, x dans enumerate(lst) :",
  },
  3291: {
    "try: fh = open(f); finally: fh.close()": "essayer : fh = ouvrir(f); finalement : fh.fermer()",
  },
  3292: {
    ".format() and % formatting": ".format() et formatage en %",
  },
  3293: {
    "Manually checking if a key exists before setting it": "Vérifier manuellement si une clé existe avant de la définir",
  },
  3294: {
    "Avoid deep nesting; prefer flat structures and early returns": "Évitez les nids profonds ; privilégiez les structures plates et les retours précoces.",
    "Lists are better than nested lists": "Les listes sont meilleures que les listes imbriquées",
    "Use only one level of imports": "N'utilisez qu'un seul niveau d'importations",
    "Never use classes inside classes": "N'utilisez jamais de classes à l'intérieur de classes.",
  },
  3295: {
    "Code should clearly show what it does": "Le code doit clairement indiquer ce qu'il fait.",
    "Always use type annotations": "Utilisez toujours les annotations de type.",
    "Never use default arguments": "N’utilisez jamais les arguments par défaut",
    "Write verbose variable names only": "N'écrivez que des noms de variables détaillés",
  },
  3296: {
    "The Zen of Python (import this)": "Le Zen de Python (importez ceci)",
  },
  3297: {
    "The Zen of Python (PEP 20)": "Le Zen de Python (PEP 20)",
  },
  3298: {
    "Easier to Ask Forgiveness than Permission": "Il est plus facile de demander pardon que la permission.",
    "Every Argument Follows Protocol": "Chaque argument suit un protocole",
    "Error And Fault Prevention": "Prévention des erreurs et des pannes",
    "Execute All Functions Promptly": "Exécutez toutes les fonctions rapidement",
  },
};

export const getTranslatedOption = (option: string, language: string, questionId: number): string => {
  if (language !== 'fr') return option;
  
  if (OPTIONS_FR[questionId] && OPTIONS_FR[questionId][option]) {
    return OPTIONS_FR[questionId][option];
  }
  
  return option;
};
